### ISSUE TITLE
Get-FlowChartNode : Gestion des erreurs lors de la lecture des fichiers

### ISSUE THREAD

**Issue by LaurentDardenne** [LxLeChat/FlowChartCore#100]
Le comportement est 'différent' pour ces deux appels :
```Powershell
Get-FLowChartNode '.\build.ps1','.\buid.ps1'
#node ..
#Get-FLowChartNode: Cannot find path 'G:\PS\FlowChartCore\buid.ps1' because it does not exist.

Get-FLowChartNode '.\buid.ps1','.\build.ps1'
#Get-FLowChartNode: Cannot find path 'G:\PS\FlowChartCore\buid.ps1' because it does not exist.
```
Le premier exemple traite le premier fichier et échoue sur le second, le traitement s'arrête.
Le second exemple échoue à traiter le premier fichier, le traitement s'arrête.

A voir si ici une erreur doit être bloquant ou pas. 
A mon avis ce type d'erreur ne doit pas être bloquant, sinon ajouter ce comportement via la paramètre[ -Strict ](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/activity-parameters?view=powershell-5.1)

> Strict
> Data type: SwitchParameter | Implement this parameter so that all errors are handled as terminating errors when the parameter is specified.

**Comment by LxLeChat** [comment]
tout à fait, cela ne devrait pas être bloquant.
je vais checker
