### ISSUE TITLE
Compatibility Mode VS Full PS V7

### ISSUE THREAD

**Issue by LxLeChat** [LxLeChat/FlowChartCore#101]
réflexion sur la compatibilité :
#74, #99, #68

- le full ps7 pas sur que c'était une bonne idée ... au final les cas spécifiques qu'on avait identifiés sont peu utilisés, et souvent dans du oneliner, ou bien via des assignations de variables ``$a = ... un truc chelou `` ce que dans tous les cas, je ne représente pas.
- ça serait dommage d'exclure PS5 ... vu que ça représente une grosse majorité des install
- la  compatibilité passerait partout ... je crois que j'ai vraiment été  bête de partir en mode exclusion PS5 !

Soit on trouve un moyen de réprésenter "graphiquement" ce genre de cas : ``$a = .... `` avec à l interieur un script block ou bien ``foreach-object  -process {}  -inputobject ...`` soit je pense que retrouver la compatibilité serait une bonne idée !

**Comment by LaurentDardenne** [comment]
Pour le #78, le ternaire sera très utilisé je pense, faut voir comment. Se contenter de la représentation d'un usage simple est un bon début.
Le #99 également mais c'est plus des JOBs une indication peut suffire ( "ça fait plein de choses presque en même temps").
Le #68 c'est le point principal. Compiler deux DLL, une par version, me semble plus facile à réaliser mais peut être plus difficile à maintenir.
Sur ce point on a le droit d'échouer, il en restera tjr qq chose. 
Le principale étant que cela reste plaisant à faire, et si je me souviens bien c'était un projet pour apprendre.
Tomber fait partie de l'apprentissage de la marche ;-)

**Comment by LxLeChat** [comment]
ahaha ! j'aime cette philosophie :) 
je n'avais même pas penser à compiler 2 dll tient ... ! 
en plus ça serait relativement simple dans le psm1 ...  détecter l'environnement c'est plutot easy ... !
Hum j'aime cette idée ! ok ok je vais me renseigner .... !

**Comment by LxLeChat** [comment]
https://medium.com/@canvascodebw/targeting-multiple-frameworks-for-c-projects-618d6db61315

bon ça n'a pas l'air si compliqué que ça

**Comment by LxLeChat** [comment]
Voila voila ... rien foutu en 1 mois et demi, et il m aura fallu 5 minutes pour le faire :)
Y a une branche framework qui contient la modif (au final c'est juste le csproj a modifié)
j'ai testé sur PS5 et ça fonctionne correctement ( importation du module + lancement des tests )

Pour l'instant il n y a aucune différenciation dans le code, puisque par exemple le ternaire n'est pas encore pris en compte. mais ça laissera la possibilité de le faire !

**Comment by LxLeChat** [comment]
[reminder]
https://docs.microsoft.com/en-us/powershell/scripting/gallery/concepts/module-psedition-support?view=powershell-7.1

lien pour charger la bonne dll en fonction de la version de PS dans le psd1

**Comment by LaurentDardenne** [comment]
Salut,
j'ai regardé rapido sur une VM au  boulot, mais ce n'est pas facile de construire le projet sans internet...
Il y a qq références de package qui ne sont pas explicité dans le fichier projet.

Les dll existantes compilées ne semblent pas fonctionner avec PS v5.1, il manque donc pour ce projet une livraison complète prête à utiliser. Ce qui est préférable si qq veut tester sans avoir à plonger dans le code ;-)

Je regarderais ce WE sur mon poste.
Et si le projet cible la v5.1 ne serait-il pas préférable d'utiliser le paquet dédié (dotNet 4.5 je crois) et pas celui nommé NetStandard ?

**Comment by LxLeChat** [comment]
Cool intéressant ! G fait ca en minutes, chez moi ça compilait correctement! Étrange 
Je checkerai aussi

**Comment by LaurentDardenne** [comment]
>>Étrange

Non pas vraiment la gestion des packages est simplifié avec un accès internet.
Sans accès j'ai créé un repo Nuget local (un simple répertoire) et l'ai configuré dans VS community, le projet compile mais remonte des [erreurs Nuget](https://docs.microsoft.com/fr-fr/nuget/reference/errors-and-warnings/nu1101) 1101.
Je n'avais pas l'envie de me lancer dans une chasse aux trésors :-)

**Comment by LxLeChat** [comment]
Ah ouais j avais pas pensé au offline effectivement...!

**Comment by LxLeChat** [comment]
Alors concernant cette issue, il a maintenant une dll pour netstandard 2.0 aussi, donc PS V5.. maintenant je vais checker pour voir le offline comme tu disais !
