### ISSUE TITLE
web interface

### ISSUE THREAD

**Issue by LxLeChat** [LxLeChat/FlowChartCore#102]
salut @LaurentDardenne 
PI j'ai commencé un ou 2 trucs rigolo, dont une azure fonction

![image](https://user-images.githubusercontent.com/43340127/113914046-5be17180-97dd-11eb-8429-3f2444b3a45f.png)

si tu veux l url je te la filerai en private (pas envie que ça soit public, surtout que c un souscription gratos que j'ai ...) !

**Comment by LaurentDardenne** [comment]
Merci de la proposition, mais pas pour le moment.

**Comment by LxLeChat** [comment]
j'ai fait un mini site static sur azure en blazor (bon j'ai adapté le template de base et je comprends pas tout ce que je fais, mais ça fonctionne et ct plutot fun ... ! ). je vais essayer d'intégrer la generation du graph avec du JS

https://ashy-ocean-0c529d303.azurestaticapps.net/

Edit:
Ajout du rendu du graph mis en place !

**Comment by LxLeChat** [comment]
Je vais clôturer pour x points:
-Je suis une quiche en design web, du coup le site ne ressemble à rien
-J'ai pas de thune et ma souscription gratuite a expiré xD

En tout ça fonctionnait parfaitement ! et j'ai gardé le code en local du coup je pourrais éventuellement le remettre en route un jour !
