### ISSUE TITLE
Notes sur AzFunction

### ISSUE THREAD

**Issue by LxLeChat** [LxLeChat/FlowChartCore#106]
Ok.
Je me suis remis sur les az functions la, et .. hum ct complexe, car en gros j'utilise une AZFunc PS... on ne peut pas faire de ``install-module`` ... j'ai donc du copier PSSA dans l'AZfunc...
à partir de la, même je chargeais le module, l'instance PS dans le code c#dédié au formattage du code ne trouvait pas le module ... !

J'ai donc du faire un truc hardcore ... ajouter un param à ``new-flochartgraph`` appelé ``PSSAPath`` ou je lui donne le chemin du psm1 de PSSA ... 

question(s)

- ~~est il possible d'utiliser les modules chargé d'une session ? (pas installé ! mais importer depuis un path ?) parce que je pense que une instance PS va automatiquement chargé le module à partir de PATH ou un truc dans le genre dans ENV...~~

- ~~peut on changer ou ajouter éventuellement dans une AZFunc un chemin par defaut ???~~

- ~~comment PS charge ces module automatiquement, ou comment sait il ou regarder encore ?? (me rappelle plus ... )~~
reponse: ``$env:PSModulePath`` et ça fonctionne aussi sur AZFunction PS !
 
[edit]Cela reste interessant !
Si aucune des reponses à ces questions ne me facilite la vie:
- est il possible de créer un build spécial pour une framework ?? genre pour le .netcore 3.1 il me faudrait 2 dll : la "classique", et une pour AZFunc.

**Comment by LaurentDardenne** [comment]
Salut,
je ne connais pas les fonctions Azure, [Ceci](https://tech.nicolonsky.ch/azure-functions-powershell-modules/) semble répondre à ta première question (dépendances).
