### ISSUE TITLE
Add Parameter Set For CodeAsText

### ISSUE THREAD

**Issue by LxLeChat** [LxLeChat/FlowChartCore#107]
Quand on utilise ``CodeAsText`` il serait bien de spécifier si on veut, oui ou non, utiliser PSSA. 
Car l'utilisation de PSSA ralentit la generation du graph.

**Comment by LxLeChat** [comment]
Enfait ce qui serait plus "intelligent"... ça serait de passer l'entièreté du code avant dans PSSA plutot que de le faire par codeblock ... ce qui prend du temps ... !

**Comment by LxLeChat** [comment]
Ok donc effectivement c bien plus intelligent de faire le formatage dans ``Get-FlowChartNode`` ...
j'ai ajouté un param ``-FormatScript``, qui fait appelle à PSSA. et j'ai sorti ce  truc de ``New-FlowCharGraph``

J'ai introduit une petite coquille (un décalage d'espace) dans un script fournit par un compère du FRPSUG!

``Get-FLowChartNode -Path C:\temp\laurent.ps1 | New-FLowChartGraph -CodeAsText`` donne:
![image](https://user-images.githubusercontent.com/43340127/118359952-e27c3200-b585-11eb-8549-5276695877d5.png)

avec formattage via PSSA
``Get-FLowChartNode -Path C:\temp\laurent.ps1 -FormatScript | New-FLowChartGraph -CodeAsText``
![image](https://user-images.githubusercontent.com/43340127/118359997-0b9cc280-b586-11eb-9a00-a23fbc8359d1.png)


qu'en penses tu @LaurentDardenne c mieux non ? :)
je n'ai pas encore poussé le code

**Comment by LxLeChat** [comment]
arf bon enfait ça fait c.... les bloc de code issue des ifs ou des boucles ne sont pas bien formattés comme ça ... retourne à la base départ !

**Comment by LaurentDardenne** [comment]
M'est avis que tu oublies le principe de base d'un cmdlet : _fait une seule chose et le fait bien_ ;-)
```Powershell
Format-Script C:\temp\laurent.ps1 | Get-FLowChartNode | New-FLowChartGraph -CodeAsText
```
[YAGNI](https://fr.wikipedia.org/wiki/YAGNI)

**Comment by LxLeChat** [comment]
Ouais sur le principe je suis tout à fait d accord avec ça :)
La c juste que formater le script avant ne resoud pas le pb d affichage pour les codeblock de niveau 2 et supérieur ! 
Bref j ai fait tellement de tests que je me suis un peu embrouillé ^^
Je vais partir sur un validateset pour codeastext, avec valeur possible: classic, format! Et voila ca fera la rue michelle!
Le format tentera d utiliser pssa ..!

**Comment by LxLeChat** [comment]
Bon du coup je clos
``CodeAsText`` est un validateSet avec 2 choix:

- Standard (n'utilise pas PSSA por formater le code des codeblock)
- Formatted (utilise PSSA pour formater le code des codeblock)
