### ISSUE TITLE
[build] v5.1 : Exception 'System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.2.0,...'

### ISSUE THREAD

**Issue by LaurentDardenne** [LxLeChat/FlowChartCore#113]
Avec la 7.1 pas de pb pour exécuter les tests.

Avec la 5.1
 ```Powershell
cd C:\Users\s850067adm\Downloads\FlowChartCore-master\Test
Invoke-Pester

[-] Discovery in C:\Users\COMPTE\Downloads\FlowChartCore-master\Test\UseCases.Tests.ps1 failed with:
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, Publ
icKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
 ```
Avec le code du repo, même erreur lors de l'import du module dans la console sous Windows Server 2012 ou Windows 10.
J'ai un doute sur le fait de ne pas tenir compte des warnings émis lors du build, mais je n'ai pas creusé le sujet, demain si je peux.

Il existe qq liens sur cette exception, mais rien de probant pour le moment.

**Comment by LaurentDardenne** [comment]
Bon, le problème est identique au build, on référence la version Core et pas celle de la plateforme courante.
[Voir](https://github.com/LxLeChat/FlowChartCore/blob/master/Test/UseCases.Tests.ps1#L31).

C'est un reste à faire qui est passé à la trappe...
Ensuite, la dll dotNetgraph est absente du répertoire de la v5.1 ( bin\Debug\netstandard2.0 )
Add-Type -path G:\PS\FlowChartCore\Src\bin\Debug\netcoreapp3.1\DotNetGraph.dll

Ensuite c'est correct.
Je vérifie à nouveau ce point demain.

**Comment by LxLeChat** [comment]
ouais pour la dll dotnetgraph j'étais au courant  ! c'est un oubli effectivement !
je vais essayé de regarder tout ce que tu as écris demain, pas sur d'avoir le temps ce soir!

**Comment by LaurentDardenne** [comment]
Sa résolution est dans le build.
