### ISSUE TITLE
Renommer le cmdlet 'Find-FLowChartNodes'

### ISSUE THREAD

**Issue by LaurentDardenne** [LxLeChat/FlowChartCore#15]
Salut,
une petite remarque en Français sur le nom du cmdlet '_Find-FLowChartNodes_'.
Ici
```Powershell
$sb={ if ($true) {$false} else {$true}}
Find-FLowChartNodes -ScriptBlock $Sb
```
La notion de FLowChartNode existe en sortie, mais en entrée on a du texte/code et on y recherche des instructions du langage (en interne des types AST) :
```c#
    public enum StatementType{
        Else,ElseIf,SwitchCase,SwitchDefault,Finally
    }
```
En calquant sur Get-Member:
```Powershell
Find-Statement -StatementType "Else,ElseIf" -Scriptblock { if ($true) {$false} else {$true}}
```
Voir Find-ConditionalStatement ( [sans S final](https://github.com/PowerShell/PSScriptAnalyzer/blob/master/RuleDocumentation/UseSingularNouns.md)) ...

Et pour ces deux constructions je supposes qu'elles ne sont pas prisent en compte à dessein :
```Powershell
$sb={ $var= if ($true) {$false} else {$true}}
Find-FLowChartNodes -ScriptBlock $Sb|New-FLowChartGraph

$sb={ $(if ($true) {$false} else {$true})}
Find-FLowChartNodes -ScriptBlock $Sb|New-FLowChartGraph
```

**Comment by LxLeChat** [comment]
Alors effectivement les noms de cmdlets sont un peu pourris ... ! c'est temporaire
je suis ouvert à toute suggestion :) ( je pense que je changerai les noms en dernier, avant de publier la 1° version sur la psgallery)
``FInd-Statement`` c'est pas mal! surtout j'aime bien l idée de choisir les statementtype... !
Je voulais d'ailleurs faire une cmdlet dédiée peut-être pour ça (#4)

Concernant ta remarque sur les constructions, effectivement elles ne sont pas prises en compte. Comme la prise en charge : ``$array | foreach-object {}`` .
Même combat pour les scriptblock dans  ``Invoke-Command``, ``Invoke-Expression``  

Après en terme de graph je vois pas trop à quoi un truc comme ça ``$sb={ $var= if ($true) {$false} else {$true}}`` pourrait ressembler

Mais les idées sont les bienvenues :)

J y ai déjà réfléchis un peu évidemment, mais ça me parait monstrueux à coder. Vu que c'est la 1° fois que j écris du c# (jump depuis PS) j'avoue que je vois pas du tout comment faire!

**Comment by LaurentDardenne** [comment]
> 
> 
> ( je pense que je changerai les noms en dernier, avant de publier la 1° version sur la psgallery)

Ce qui oblige à modifier tous les scripts ;-)
Je préfère les nommer avant, quitte à les changer si besoin.

> Je voulais d'ailleurs faire une cmdlet dédiée peut-être pour ça (#4)
> 
J'ai vue après avoir posté. Bien que pour ton projet j'ai un peu de mal à comprendre ton objectif et l'usage de ce soft.

> Après en terme de graph je vois pas trop à quoi un truc comme ça `$sb={ $var= if ($true) {$false} else {$true}}` pourrait ressembler
> 
Oui cette construction n'a pas trop de sens, mais les spec du langage l'autorise.
Cela permet de connaitre ce qui est considéré et ce qui ne l'est pas. De plus on ne sait jamais comment est écrit le code que l'on souhaite analyser.

> 
> J y ai déjà réfléchis un peu évidemment, mais ça me parait monstrueux à coder. 
>

Sans trop connaitre l'objectif je ne sais pas, mais déjà de recenser les possibles constructions consoliderait le projet je pense.
Car ici sans code de démo, [je me suis retrouvé comme une poule devant une fourchette](https://www.jesuisundev.com/ecris-ta-documentation-technique-bordel-de-merde/) :-)
Mais ayant précédemment regardé tes autres projets, je suis retombé, un peu, sur mes pattes.
Par exemple on ne sait pas qu'il faut PS Core, que les DLL dépendantes sont à chargées manuellement.

>Vu que c'est la 1° fois que j écris du c# (jump depuis PS) j'avoue que je vois pas du tout comment faire!
>
De savoir ce que l'on doit faire est un bon début ;-)

**Comment by LxLeChat** [comment]
l'idée c'est que de pouvoir documenter automatiquement des script par exemples. oui les commentaires son suffisants, mais j'aime bien avoir une représentation graphique des choses. En fait j'ai déja rencontré le cas je me suis retrouvé face à des scripts gigantesques sans explications et sans commentaire et vas y débrouille toi :)

l'idée que je trouve sympa aussi c'est si t as un source control ou son stockés tes script, tu peux imaginer automatique generéer des graphs des scripts et les deposer quelque part.. pour d'autres personnes à vrai dire :) pas que pour la personne qui a écrit le script. !



PSCore n'est pas obligatoire, ça fonctionne sous PS5 aussi :) et normalement tu n as pas a charger les dll dépendantes ! mais oui je vais ajouter tout ça dans le readme

**Comment by LaurentDardenne** [comment]
> 
> 
> l'idée c'est que de pouvoir documenter automatiquement des script par exemples. 

Ok, c'est un travail difficile avec Powershell, mais ce n'est pas plus facile de documenter du C#...

> j'aime bien avoir une représentation graphique des choses. 

Pour retrouver les dépendances et la structure globale oui cela a déjà plus de sens, non pas qu'ici cela n'en ai pas mais en l'état on reste dubatif sur l'objectif.

>En fait j'ai déja rencontré le cas je me suis retrouvé face à des scripts gigantesques sans explications et sans commentaire et vas y débrouille toi :)
>
J'ai la carte du club...

> 
> ... tu peux imaginer automatiquement generer des graphs des scripts 
> 
La difficulté ici est de savoir ce que l'on gére comme informations et pour quel niveau de détail.
Sur un projet où j'ai du code PS manipulant du WPF dynamique et du SQL dynamique d'avoir des graphes m'aurait peut être aidé au début, mais au lieu de me noyer dans du code je me serais noyé dans des graphes ;-)

> PSCore n'est pas obligatoire, ça fonctionne sous PS5 aussi :) et normalement tu n as pas a charger les dll dépendantes ! mais oui je vais ajouter tout ça dans le readme
>
Exact, les fichiers DLL sont bloquées, mais sous PS core ça passe sans les débloquer :-/

**Comment by LxLeChat** [comment]
> La difficulté ici est de savoir ce que l'on gére comme informations et pour quel niveau de détail.
Sur un projet où j'ai du code PS manipulant du WPF dynamique et du SQL dynamique d'avoir des graphes m'aurait peut être aidé au début, mais au lieu de me noyer dans du code je me serais noyé dans des graphes ;-)

Effectivement, je vais ajouter un truc dans le readme pour préciser dans quel genre ce situation c'est approprié d'utiliser ce module.

**Comment by LxLeChat** [comment]
cmdlet renommée
