### ISSUE TITLE
L'imbrication de IF n'est pas correctement représenté.

### ISSUE THREAD

**Issue by LaurentDardenne** [LxLeChat/FlowChartCore#16]
Salut,
l'imbrication de IF n'est pas correctement représenté.

Version sans imbrication :
```Powershell
$sb={
	try{
		faitqqchose
		$PSDrive = $global:conf
		
		if((Get-PSDrive -Name $PSDrive -ea Ignore) -eq $null)
               {
			writeLog "Mount PSDrive: $PSDrive"
            #   !!!!!!!! Pas d'imbrication de test  !!!!!!!!!!!
		}

		if($processStatus -eq $false){
			throw $errorMessage
		}

		if($processStatus -eq $true){
			Push-Location "$($PSDrive):"
		}
	}catch{
		throw $_
	}
}
Find-FLowChartNodes -ScriptBlock $Sb|New-FLowChartGraph  > c:\temp\test.graph
C:\Tools\Graphviz\bin\dot -Tpng c:\temp\test.graph -o c:\temp\test.png
ii c:\temp\test.png
```
Version avec une imbrication :
```Powershell
$sb={
	try{
		faitqqchose
		$PSDrive = $global:conf
		
		if((Get-PSDrive -Name $PSDrive -ea Ignore) -eq $null)
               {
			writeLog "Mount PSDrive: $PSDrive"
			if((Test-Connection $SCCMServer -Count 2 -Quiet) -eq $false)
            { writeLog ("{0} is unreachable" -f $SCCMServer) }
            else
            { 
                writeLog ("server respond")
				if($remoteAuth -eq $false)
                {
                    writeLog ("no credential")
					if((New-PsDrive -Name $PSDrive -PSProvider CMSite -Root $SCCMServer -Scope Global) -eq $null)
                    { $errorMessage = $CannotMountPSDrive}
				}
                else
                { 
                     writeLog ("with credential")
					if((New-PsDrive -Name $PSDrive -PSProvider CMSite -Root $SCCMServer -Scope Global -Credential $credentials.$env) -eq $null)
                    { $errorMessage = $CannotMountPSDrive }
				}
			}
		}

		if($processStatus -eq $false){
			throw $errorMessage
		}

		if($processStatus -eq $true){
			Push-Location "$($PSDrive):"
		}
	}catch{
		throw $_
	}
}
Find-FLowChartNodes -ScriptBlock $Sb|New-FLowChartGraph  > c:\temp\testNested.graph
C:\Tools\Graphviz\bin\dot -Tpng c:\temp\testNested.graph -o c:\temp\testNested.png
ii c:\temp\testNested.png
```
A priori il manque un 'conteneur' pour représenter l'imbrication de if.
![image](https://user-images.githubusercontent.com/4894452/95774702-2ee65300-0cc1-11eb-9e12-bd584ba68282.png)

Les deux parties encadrées d'orange devrait être liées directement il me semble.

Le code d'origine est formaté dans VS mais ici il ne l'est plus...

**Comment by LaurentDardenne** [comment]
J'ajoute ce cas qui me semble lié au probléme précédent :
```powershell
$sb={
    $grade = 92
    if ($grade -ge 90) { "Grade A" }
    writeLog "Suite"

}
del c:\temp\testWithIF2.graph, c:\temp\testWithIF2.png -ea Ignore

Find-FLowChartNodes -ScriptBlock $Sb|New-FLowChartGraph  > c:\temp\testWithIF2.graph
C:\Tools\Graphviz\bin\dot -Tpng c:\temp\testWithIF2.graph -o c:\temp\testWithIF2.png
ii c:\temp\testWithIF2.png
```
La présence de code précédent le IF est représenté mais pas celui siuté après : 
![image](https://user-images.githubusercontent.com/4894452/95778461-73c1b800-0cc8-11eb-882a-9b81c87d5cc9.png)

**Comment by LxLeChat** [comment]
Top merci pour les exemples !

**Comment by LxLeChat** [comment]
effectivement, il me manquait des block "code" ... !
j'ai mergé vers la master pour faciliter les choses, je te laisse tester si tu as envie avant de clôturer.

petite astuce, si tu veux aller vite : ``Find-FlowChartNodes -Scriptblock $sb |  New-FlowChartGraph | Set-Clipboard``
Ensuite perso je paste tout ça ici: http://dreampuf.github.io/GraphvizOnline

**Comment by LaurentDardenne** [comment]
> 
> ...je te laisse tester si tu as envie avant de clôturer.
>
Le cas sur le _If_ ne me semble pas avoir changé, je ne sais pas si tu comptes ajouter une notion de sous-graph.
Peut être considères-tu que l'ajout d'un élément CodeBlock ne se fait que si on a une ou des instructions après le if/else ?
Dans l'exemple suivant on ajoute des instructions après le bloc If/Else:
```Powershell
$sb={
		faitqqchose
		$PSDrive = $global:conf
		
		if((Get-PSDrive -Name $PSDrive -ea Ignore) -eq $null)
        {
			writeLog "Mount PSDrive: $PSDrive"
			if((Test-Connection $SCCMServer -Count 2 -Quiet) -eq $false)
            { writeLog ("{0} is unreachable" -f $SCCMServer) }
            else
            { 
                writeLog ("server respond")
				if($remoteAuth -eq $false)
                {
                    writeLog ("no credential")
					if((New-PsDrive -Name $PSDrive -PSProvider CMSite -Root $SCCMServer -Scope Global) -eq $null)
                    { $errorMessage = $CannotMountPSDrive}
				}
                else
                { 
                     writeLog ("with credential")
					if((New-PsDrive -Name $PSDrive -PSProvider CMSite -Root $SCCMServer -Scope Global -Credential $credentials.$env) -eq $null)
                    { $errorMessage = $CannotMountPSDrive }
                }
                writeLog ("Inner suite") 
            }
           writeLog ("Main suite") 
		}
		if($processStatus -eq $false){
			throw $errorMessage
		}

		if($processStatus -eq $true){
			Push-Location "$($PSDrive):"
		}        
}
Find-FLowChartNodes -ScriptBlock $Sb|New-FLowChartGraph  > c:\temp\testNested.graph
C:\Tools\Graphviz\bin\dot -Tpng c:\temp\testNested.graph -o c:\temp\testNested.png
ii c:\temp\testNested.png
```
On obtient en visu ceci :
![image](https://user-images.githubusercontent.com/4894452/95887576-4df7ea00-0d80-11eb-8ffc-30e6eafc25d1.png)
Dans ce graphe on a trois nouveaux éléments 'CodeBlock' dont deux représentant la même portion de code alors que le If est inclus dans ce codeblock. Ici il devrait y avoir un sous graph (un conteneur: un scriptblock contient un autre scriptblock).
J'ai lu que tu souhaitais gérer la [profondeur d'analyse](https://github.com/LxLeChat/FlowChartCore/issues/3), c'est lié je pense. Ici _pour aller plus loin, faut aller plus près_ .

Le rendu dans VS
> 
> petite astuce, si tu veux aller vite 
>
_"celui qui prend son temps n'en manque jamais."_
On peut ne pas avoir d'accès internet sur des machines de test.
Mais de coder des chemins en dur ne t'aide pas, j'en suis conscient.

ps:
Avec le format utilisé par Graphviz le rendu est statique, alors que DGML permet de "fermer/ouvrir" cette notion d'élément conteneur.

**Comment by LxLeChat** [comment]
ah excuse moi, y a un switch ``-codeastext`` sur new-flochartgraph .qui remplacere codeblock par le vrai code
t'es sur slack à tout hasard ?

![image](https://user-images.githubusercontent.com/43340127/95891140-eee8a400-0d84-11eb-8817-b9ce08ee5a0e.png)


voila ce que ça donne avec le "-codeastext"

**Comment by LaurentDardenne** [comment]
>t'es sur slack à tout hasard ?
>
Non, je l'ai utilisé pour le frpsug, mais je préfère le mail, ça laisse le temps de réfléchir :-)

**Comment by LaurentDardenne** [comment]
L'usage du switch _-codeastext_ modifie le rendu du codeblock mais n'ajoute pas une gestion des [subgraphs](https://stackoverflow.com/questions/2012036/graphviz-how-to-connect-subgraphs)

**Comment by LaurentDardenne** [comment]
De plus en utilisant ce switch j'ai une erreur de _dot.exe_ : 
 _Error: c:\temp\testNested.graph: syntax error in line 1 near ' ■d'_

Je n'ai pas le temps de creuser, peut être un formatage erroné...

**Comment by LxLeChat** [comment]
Je sais que g un bug aussi sur le codeastext quand jai codeblock en dernière position!
Je vais checker tout ça

**Comment by LaurentDardenne** [comment]
> 
> 
> De plus en utilisant ce switch j'ai une erreur de _dot.exe_ :
> _Error: c:\temp\testNested.graph: syntax error in line 1 near ' ■d'_
> 
> Je n'ai pas le temps de creuser, peut être un formatage erroné...

En PS v5.1 la redirection enregistre avec le fichier un BOM, l'usage de Set-Content résout le pb.

**Comment by LxLeChat** [comment]
du coup on peut clôturer ?
