### ISSUE TITLE
A propos du rendu de l'instruction catch

### ISSUE THREAD

**Issue by LaurentDardenne** [LxLeChat/FlowChartCore#21]
Pour ce code : 
```powershell
@'
try {
 $grade = 92
} 
catch [System.ExecutionEngineException] {}
"suite"
'@ |set-content  -path  c:\temp\catch.ps1

$Result=Find-FLowChartNodes -path c:\temp\catch.ps1
New-FLowChartGraph  $Result |Set-Content  c:\temp\Catch.graph
C:\Tools\Graphviz\bin\dot -Tpng c:\temp\Catch.graph -o c:\temp\catch.png
ii c:\temp\Catch.png
```
on obtient : 
![image](https://user-images.githubusercontent.com/4894452/95909221-6bd44780-0d9e-11eb-9093-9e4800d8a60c.png)

Je pense que le rendu suivant porte mieux la notion des 2 scénarios, un sans erreur et l'autre avec erreur :  
![image](https://user-images.githubusercontent.com/4894452/95909471-d5545600-0d9e-11eb-8244-303380af1804.png)

La création de ces 2 possibles  chemins se fait sur le nœud _codeblock_ pas et sur le noeud _Try_.

Fichier adapté :
```
digraph "a" { 
	"01"[label="Try"]; 
	"end_01"[shape=mdiamond,label="End Try"]; 
	"01" -> "0110"[label="Catches Error"]; 
	"end_01" -> "02"; 
	"0110"[label="CodeBlock Code"]; 
	"0110" -> "end_01"; 
	"0110" -> "0111"; 
	"0111"[label="Catch"]; 
	"0111" -> "011120"; 
	"011120"[label="CodeBlock exception"]; 
	"011120" -> "end_01"; 
	"02"[label="CodeBlock"]; 
	"02" -> "end_of_script"; 
}
```
[edit]
On doit d'abord passer par le codeblock pour déclencher le catch.

**Comment by LaurentDardenne** [comment]
Autre intérêt,  un bloc _Catch_ ou _Finally_ ne peut être placé que s'il existe une instruction _Try_, sa présence est donc implicite ( dans le cas contraire on a une erreur de syntaxe, donc pas de génération de graphe).
Avec la seconde instruction on peut envisager de simplifier en supprimant la génération du noeud _Try_, à voir si cela resterait lisible avec d'autres constructions...

**Comment by LxLeChat** [comment]
Alors sur le principe je suis d'accord avec ta représentation. Je crois que j'avais commencer comme ça.
Mais le soucis c'est lorsque tu vas avoir plus de code dans ton try c'est que ça va compliqué les choses ... il faudrait que chaque enfant du try pointent vers le catch (en soit c pas compliqué à implémenter) mais d'un point de vu rendu ça sera pas très propre.

**Comment by LaurentDardenne** [comment]
Ok je regarderais une construction plus élaborée.

**Comment by LaurentDardenne** [comment]
Pour une construction Try/Catch plus élaborée, la génération manuelle du graphe est trop chronophage. je ne peux donc comparer, à moins de le coder.
Je pense que le fait de ne pas utiliser de sous-graphe pour représenter ce type d'imbrication apporte une verbosité au niveau des nœuds.
Exemple plus élaboré (une imbrication de structure identique) : 
```powershell
$sb={
    "deux"
    try {
     $grade = 92
    } 
    catch [System.ExecutionEngineException] {
            "deux"
            try {
                    $grade = 92
                    if ($grade -ge 90) { "Grade A" }
                    elseif ($grade -ge 80) { "Grade B"} 
                    elseif ($grade -ge 70) { "Grade C";break}
                    elseif ($grade -ge 60) { "Grade D" }
                    else { "Grade F"}
                    writeLog "Suite"
                    break
            } 
            catch [System.ExecutionEngineException] {"un"}
            catch [System.IO.DirectoryNotFoundException] {"deux"}
            catch {"trois"}
            Finally {
                "dispose"
            }
    }
    catch [System.IO.DirectoryNotFoundException] {
            "deux"
            try {
                $grade = 92
                if ($grade -ge 90) { "Grade A" }
                elseif ($grade -ge 80) { "Grade B"} 
                elseif ($grade -ge 70) { "Grade C";break}
                elseif ($grade -ge 60) { "Grade D" }
                else { "Grade F"}
                writeLog "Suite"
                break
            } 
            catch [System.ExecutionEngineException] {"un"}
            catch [System.IO.DirectoryNotFoundException] {"deux"}
            catch {"trois"}
            Finally {
                "dispose"
            }
    }
    catch {
            "deux"
            try {
                $grade = 92
                if ($grade -ge 90) { "Grade A" }
                elseif ($grade -ge 80) { "Grade B"} 
                elseif ($grade -ge 70) { "Grade C";break}
                elseif ($grade -ge 60) { "Grade D" }
                else { "Grade F"}
                writeLog "Suite"
                break
            } 
            catch [System.ExecutionEngineException] {"un"}
            catch [System.IO.DirectoryNotFoundException] {"deux"}
            catch {"trois"}
            Finally {
                "dispose"
            }
    }
    Finally {
            "deux"
            try {
                $grade = 92
                if ($grade -ge 90) { "Grade A" }
                elseif ($grade -ge 80) { "Grade B"} 
                elseif ($grade -ge 70) { "Grade C"}
                elseif ($grade -ge 60) { "Grade D" }
                else { "Grade F"}
                writeLog "Suite"
            } 
            catch [System.ExecutionEngineException] {"un"}
            catch [System.IO.DirectoryNotFoundException] {"deux"}
            catch {"trois"}
            Finally {
                "dispose"
            }
    }
}
```

Le rendu : 
![image](https://user-images.githubusercontent.com/4894452/96454045-98afb100-121b-11eb-9409-e253a87ea17e.png)

Autre possibilité, si ce qui m'intéresse est le scénario 'des beaux jours' (quand tout ce passe bien), permettre de ne pas afficher le détail du _Try/Catch_.
Rendu que l'on peut avoir dans VS Code : 
![image](https://user-images.githubusercontent.com/4894452/96455576-b3832500-121d-11eb-944f-bc76eadf25c4.png)

**Comment by LxLeChat** [comment]
hin je vois ce que tu veux dire ..., bah ça va un peu avec les histoires de profondeur de graph ... enfait si on inclus un truc comme ça, il faudrait que tout ce qu'il y a dans un catch soit rendu sous forme de codeblock au moment de la generation du graph .. !

je vais créer une issue pour déja afficher les  exception "catcher"

**Comment by LaurentDardenne** [comment]
> ça va un peu avec les histoires de profondeur de graph

On masque certaines constructions. On peut parcourir tout les chemins de code mais ne pas tout détailler.
Par exemple ici je veux détailler ce que 'fait' un script, pas ce qu'il fait quand il y a une erreur.
