### ISSUE TITLE
[Question] Gestion des fonctions 

### ISSUE THREAD

**Issue by LaurentDardenne** [LxLeChat/FlowChartCore#26]
Le code suivant n'analyse pas le code de la fonction : 
```powershell
$sb={
 function test { if ($true) {'ok'}}
}

$Temp='C:\temp'
$GraphvizPath='C:\Tools\Graphviz\bin\'
$ModulePath='C:\Users\Laurent\Downloads\FlowChartCore\Code\bin\Debug\netstandard2.0'
Cd $ModulePath
unblock-File "$pwd\DotNetGraph.dll"
unblock-File "$pwd\FlowchartCore.dll"
#first time, close and open PS console

ipmo .\DotNetGraph.dll,.\FlowchartCore.dll

$TestFileName='NestedCatch'
$FileName="$Temp\$TestFileName"

$run={
Find-FLowChartNodes -ScriptBlock $Sb|New-FLowChartGraph |Set-Content "$FileName.graph"
&"$GraphvizPath\dot.exe" -Tpng "$FileName.graph" -o "$FileName.png"
ii "$FileName.png"
}
&$run
```
![image](https://user-images.githubusercontent.com/4894452/96169996-47ee3e80-0f23-11eb-915f-b9c49a368b45.png)

Est-ce prévue ?
Et l'analyse d'un module contenant des fonctions ?

**Comment by LxLeChat** [comment]
si tu utilisie le ``-codeastext`` tu verras la déclaration de la fonction dans le codeblock ... j'ai créé une issue dédié à tout ça ou je 
parle de ce qu on pourrait éventuellement penser à faire, ce que j'avais déja tenté etc.. #27 
mais en gros j avais déja tenté les déclaration de fonctions.. c'est carrement faisaible mais si je l ai retiré c'est qu il y avait un truc ... je sais plus ce que c'était ...

**Comment by LxLeChat** [comment]
Ce qui pourrait etre rigolo c est d ajouter ca https://github.com/LxLeChat/PSFunctionExplorer

Comme ça on pourrait ajouter un outil a la boite... ca deviendrait donc une boite à outils 😀 

Avec une cmdlet indépendante évidemment

**Comment by LaurentDardenne** [comment]
Il y a ceci qui pose pb avec _PSFunctionExplorer_ : 
```powershell
Function Test-Three {
  Function Test-One {
    Function Test-Two {
    }
   Test-Two
  }
  Test-One
 }

 Function Test-Three2 {
  Function Test-One {
    Function Test-Two {
    }
   Two
  }
  One
 }

#Imbrication ET dans le même scope
Function Test-NestedThree {


  Function Test-NestedOne {
  }

  Function Test-NestedTwo {
  }
  
  Test-NestedOne
  Test-NestedTwo
}

#dans le même scope
Function Test-OneStandAlone {
}

Function Test-TwoStandAlone {
}

Function Test-ThreeStandAlone {
  oneStandAlone 
  twoStandAlone
}

#Appel externe
Function Test-Four {
    Function Test-Inner {
     TwoExternal
  }
  OneExternal
 }
```
A placer dans un script.
Pour moi c'est les relations entre fonction qui m'importe et m'apporte une aide. Dans le graph généré je ne vois que les appels de fonction et il ne tient pas compte du scope. Et si on utilise le nom de fonction comme identifiant de nœud on a très vite des pb car un nom est unique dans le graph.C'est un peu tordu comme exemple, mais possible.

Ici la simple possibilité de parcourir le code d'une fonction permettrait de tester de nombreux scenarios facilement sans devoir les écrire. Par exemple lire le répertoire Modules natif et ceux provenant de la Gallery. PSFunctionExplorer c'est autre besoin.

**Comment by LxLeChat** [comment]
Ce qu on pourrait faire c est créer un noeud de type FunctionNode qui correspondrait a une définition de fonction. 
Cela permettrait de voir qu il y a des déclarations de fonctions sans forcément afficher dans un noeud code toute la définition de la dite fonction!

Apres si on se dit: on veut voir la définition de la fonction on ajoute un switch sur new-flowchart

**Comment by LaurentDardenne** [comment]
> Après si on se dit: on veut voir la définition de la fonction on ajoute un switch sur new-flowchart

Oui, cela revient à traiter la profondeur. La profondeur d'analyse étant différente de l'affichage des détails.
On peut avoir des fonctions imbriquées avec ou sans gestion des blocs _Begin/Process/End_.

De pouvoir traiter le corps d'une fonction ce serait déjà bien. En traitant toutes les fonctions d'un module on est assuré d'avoir un gros paquet de nœud illisible dans un seul schéma.

On a donc : 
 

- une fonction dans un script,
-  une fonction dans une fonction dans un script,
-  des fonctions dans un script,
-  des fonctions dans un module

.

Le besoin étant "donne moi les fonctions ('de premier niveau') présent dans ce 'conteneur de code'.
Ceci permettrait d'analyser de nombreux scripts afin d'enrichir les scénarios de tests.

**Comment by LxLeChat** [comment]
Oui ça serait ca l idée uniquement les fonctions de premier niveau

**Comment by LxLeChat** [comment]
alors,
pour le bloc scriptblock suivant:
```powershell
$sb = {
    $i = 1

function plop {
	"ahahah"
}
}
```

avec ``find-flowchartnodes`` on obtient le résultat suivant
```powershell
PS > Find-FLowChartNodes -ScriptBlock $sb

Name     : CodeNode
Children : {}      
Parent   :
Position : 1       
Depth    : 0       
Id       : 01
Graph    : {}

FunctionName : plop
Name         : FunctionNode
Children     : {}
Parent       :
Position     : 2
Depth        : 0
Id           : 02
Graph        : {}
```

pour l'instant j'ai pas créer la partie graph, mais je compte partir sur un truc assez simple pour le moment, un carré avec marqué: "Function X" voila ..
Je vais pousser ça sur une nouvelle branche ``FunctionNode``

Si tu redeclares des fonctions dans ta fonciton, elles ne seront pas prises en comptes. Mais ça laisse ouvre la possibilité

**Comment by LxLeChat** [comment]
bon voila j'ai implémenté la création du graph, après je peux mettre une forme dédiée ce type de noeud

![image](https://user-images.githubusercontent.com/43340127/97364742-c55f6a80-18a4-11eb-926b-aafdc0a6246d.png)

**Comment by LxLeChat** [comment]
J avais fait ça mais j ai butté la branche :) bon c assez simple a remettre en place si nécessaire

**Comment by LaurentDardenne** [comment]
> J avais fait ça mais j ai butté la branche :) bon c assez simple a remettre en place si nécessaire

L'objet _Node_ portant la fonction contient-il l'AST du corps de la fonction ?
Si ce n'est pas le cas on doit analyser chaque corps de fonction et le passer _Find-FLowChartNodes_.
C'est une possibilité, faut juste le documenter.

**Comment by LxLeChat** [comment]
Chaque object node, contient toujours l'AST du type. alwaaaaaaaays !
tu peux le vérifier en appellant la methode ``GetAst()`` sur un noeud (bien qu'il me semble que j'ai parfois oublier de l'implémenter sur certains types de noeud )

**Comment by LaurentDardenne** [comment]
> 
> 
> Chaque object node, contient toujours l'AST du type. alwaaaaaaaays !

Dans ce cas rétabli ce que tu avais fait.
On peut peut-être recréer l'arborescence sur le FileSystem et pas dans le graph, je regarde si cela apporte qq chose.

**Comment by LxLeChat** [comment]
ce qui serait interessant ... c'est d'avoir la possibilité quand on génère les graphs avec ``new-flowchartgraph`` c'est d'avoir un switch, un peu comme ``codeastext`` mais pour les fonctions, du genre ``functionasgraph`` et que ça génère des definitions par fonctions (comme ça on pourrait avoir des fichiers séparé pour les fonctions) tout en gardant le fichier "principal"

par exemple, 1 script avec 2 fonctions dedans, cela nous donnerait une definition pour le script, et 2 definitions supplémentaires, une par fonction

**Comment by LxLeChat** [comment]
j"ai créé une branche dédiée qui s'appelle function https://github.com/LxLeChat/FlowChartCore/tree/Function

[edit] Si tu trouves ça cool, je vais mettre un tit coup de collier pour merger au moins ça, et ensuite faire une 1° publication sur la ps gallery. le CI fonctionne, il va valloir voir vérifier que tout fonctionne et après bum!

**Comment by LaurentDardenne** [comment]
Merci.
Ce code : 
```powershell
@'
function Get-Main{
   function nestedOne {
      function nestedTwo{
         Get-MyDatas 
      }
      nestedTwo 
   }
nestedOne
}
function set-datas {
   Get-MyDatas
} 

function Get-MyDatas{
} 

Get-Main
'@ > c:\temp\CallMainFunctionInsideNestedFunction.ps1
```
avec l'appel l'appel suivant :
```Powershell
$Env:GRAPHVIZ_DOT='C:\Tools\Graphviz\bin'
Find-FLowChartNodes -Path c:\temp\CallMainFunctionInsideNestedFunction.ps1|New-FLowChartGraph -CodeAsText > c:\temp\t.dot
&"$Env:GRAPHVIZ_DOT\dot.exe" -Tpng c:\temp\t.dot  -o "c:\temp\t.png"
ii "c:\temp\t.png"
```
génère
![image](https://user-images.githubusercontent.com/4894452/99192499-7b66f780-2773-11eb-937f-fc851065a1c0.png)

Pour cette exemple _-CodeAsText_ est correct mais inapproprié car il englobe tout le code du script.
Le pointeur du code a afficher, s'il n'est pas un nœud reconnu, devrait se placer sur le dernière caractère de fin de déclaration de fonction.
Sous PS pour utiliser une fonction on doit au préalable la définir ( il n'y a pas de déclaration [forward](https://fr.wikipedia.org/wiki/D%C3%A9claration_avanc%C3%A9e)). FlowChartCore ne gère que du 'statique'.
La plupart du code des modules suivent ce type d'écriture il me semble.

> Si tu trouves ça cool, je vais mettre un ptit coup de collier pour merger au moins ça, et ensuite faire une 1° publication sur la ps gallery. le CI fonctionne, il va falloir voir vérifier que tout fonctionne et après bum!

C'est peut être un peu prématuré (pas d'aide US, pas de projets de démo), mais tu fais comme tu veux :-)

> ce qui serait intéressant ... c'est d'avoir la possibilité quand on génère les graphs avec `new-flowchartgraph` c'est d'avoir un switch, un peu comme `codeastext` mais pour les fonctions, du genre `functionasgraph` et que ça génère des définitions par fonctions (comme ça on pourrait avoir des fichiers séparé pour les fonctions) tout en gardant le fichier "principal"

Si l'objectif est de documenter le flux, le code des fonctions ne doit pas être pas être dans le diagramme.
Je pensais que c'était une bonne idée, mais ce n'est plus du tout le même outil.

>comme ça on pourrait avoir des fichiers séparé pour les fonctions

On peut les obtenir mais il faut coder en dehors du projet. Et par le même vérifier s'il le permet.

**Comment by LxLeChat** [comment]
effectivement joli bug ! je vais corriger :)

**Comment by LxLeChat** [comment]
Voila j'ai ameliorer le truc
![image](https://user-images.githubusercontent.com/43340127/99198773-17582980-279b-11eb-95e4-d23974375f59.png)

**Comment by LaurentDardenne** [comment]
A voté !

> Voila j'ai amélioré le truc

Certains améliorent l'ordinaire, d'autres l'existant :-)

**Comment by LxLeChat** [comment]
Ahah :)
Je mergerai ce soir!

**Comment by LxLeChat** [comment]
merger dans dev et master
