### ISSUE TITLE
Type de Graph

### ISSUE THREAD

**Issue by LxLeChat** [LxLeChat/FlowChartCore#29]
Intégrer de novueau type de graph ? DGML par exemple
J'avais commencé pour generer du Mmd (Mermaid)

La question que je me pose est la suivante: est ce que j'ai bien fait les choses pour pouvoir intégrer de nouveaux type de graph ?? 

et c'est la ou sont mes limites en dev :) c'est aussi l'occasion d'apprendre des novueaux trucs !

**Comment by LaurentDardenne** [comment]
Salut, 
> Intégrer de nouveau type de graphe ? DGML par exemple

DGML est un format. 
On génère un graphe, on le transforme dans un format puis on l'affiche à l'aide d'un outil.

> J'avais commencé pour générer du Mmd (Mermaid)

Il semble autoriser de nombreuses représentations.

> La question que je me pose est la suivante: est ce que j'ai bien fait les choses pour pouvoir intégrer de nouveaux type de graph ??

Je n'ai pas lu le code, mais déjà si tu as décomposé, oui probablement. Si on analyse insuffisamment les cas ni ne délimite clairement les objectifs ça peut arriver.
C'est plus une question de conception que de codage.
Et je ne sais pas si en parlant de type de graphe tu parles de [ceci](https://fr.wikipedia.org/wiki/Graphe_(math%C3%A9matiques_discr%C3%A8tes)#Types_de_graphes) ou si c'est de types de relation entre éléments de l'AST ?

> et c'est là où sont mes limites en dev :) 

T'es pas le seul, [un peu d'humilité](https://www.ndepend.com/docs/visual-studio-dependency-graph) ça aide ;-)

>c'est aussi l'occasion d'apprendre des nouveaux trucs !

[Oui](https://www.jesuisundev.com/projet-perso/)

**Comment by LxLeChat** [comment]
Oui pardon, être en capacité de sortir différents format

> C'est plus une question de conception que de codage.
tout à fait, et je sais pas si j'ai bien conçu le truc .. ! 
déja j'ai des classes qui permette de g rapher par type de noeud ...
![image](https://user-images.githubusercontent.com/43340127/96304505-89065180-0ffc-11eb-9779-67bc40c9820c.png)

voila comme c'est fait par exemple, mais du coup je pense qu'il faudrait une sous classe par type
du style : 

public class BreakBuilder.Dot 
public class BreakBuilder.Mmd
public class BreakBuilder.Dgml

début d'idéee .. ! 

ou une classe dédiée .... à part et on passe un type
je ne sais pas trop ! design pattern à la rescousse

**Comment by LaurentDardenne** [comment]
> je pense qu'il faudrait une sous classe par type

Je ne pense pas que ce soit la bonne approche.
Si je souhaite générer un format différent il faut pouvoir parcourir le graphe afin de connaitre les relations entre les nœuds : 

- _Find-FLowChartNodes_ renvoit une liste de noeuds, pas un graph.
- _New-FLowChartGraph_ construit un graph à partir de cette liste puis renvoit le résultat (une string/format dot) du parcourt du graph ( si je ne me trompe pas).

Il manque l'accès au graph, sans transformation. A partir de là je peux créer, à l'aide de code externe à ton projet, un fichier dans un format particulier consommé par un outil de rendu. Et c'est toujours plus facile à dire qu'a faire...


Ce qui importe, il me semble, dans cet exercice est de parcourir l'AST, un arbre (lien Parent/Enfants), et de le transformer en un graph (qui lui facilite la construction des relations entre Parents/Enfants, Parents/Parents, etc).

J'avais utilisé la classe [digraph de PSSA](https://github.com/bergmeister/PSScriptAnalyzer/blob/39b81a8823da39407310fa0693c4d94faa0895ad/Tests/Engine/Helper.tests.ps1) pour porter les relations entre fonctions voir les dépendances, mais ce n'est pas peut être pas l'objectif de ce projet.

**Comment by LxLeChat** [comment]
En parlant de ca j avais un teuc dans le genre 

https://github.com/LxLeChat/PSFunctionExplorer

Enfait je pense que mon vocabulaire n est pas le bon :) j aurai du dire type de rendu ou definition...tu vois ce que je veux dire? 
J aimerai pouvoir, a terme, faire un truc du genre ``new-flowchartcore -type dot|mmdd|..``

Mais j ai l impression qu il doit me manquer une notion ... 
oui ``find`` renvoie des noeuds et l autre ``new`` construit un graph et renvoie une string

J ai regarder un peu pssa hier mais je me suis perdu :)

Oui effectivement le but est de parcourir l'AST, mais aussi que j apprenne des nouvelles notions. En l'occurrence avec cet exercice d'implémenter différents types de "graph", c'est de voir comment organiser au mieux le code et éventuellement et d'apprendre un peu les design pattern ..  j imagine que tu sais très bien ce que c'est, mais je me suis inspiré de ce site https://refactoring.guru/design-patterns pour m'aider à construire tout ça

**Comment by LaurentDardenne** [comment]
Pour PSFunctionExplorer oui j'avais vu l'année dernière, je comptais lui soumettre qq constructions pour voir comment il réagissait.

>J'aimerai pouvoir, à terme, faire un truc du genre new-flowchartcore -type dot|mmdd|.

Selon moi un cmdlet fait une chose à la fois avec parfois plusieurs comportements. [PScribo](https://github.com/iainbrighton/PScribo) propose Export-Document pour cette usage.

>>J'ai regarder un peu pssa hier mais je me suis perdu 

Oui c'est dense. L'équipe est en train de le réécrire, espérons que ce soit plus facile à comprendre.

>j imagine que tu sais très bien ce que c'est

Oui, mais je code principalement en PS et auparavant j'ai fait bcp de plus de maintenance que de projets de A-Z, ce qui fait que je n'en ai pas codé des masses. Je sais ce que c'est, le _très bien_ pas encore ;-)

**Comment by LxLeChat** [comment]
> Selon moi un cmdlet fait une chose à la fois avec parfois plusieurs comportements. PScribo propose Export-Document pour cette usage.

oui, mais la en l'occurrence tout se passerait dans les classes, la cmdlet elle sortirait toujours du string, tu specifie le type que tu souhaite avoir et tu fournis ça en param de la méthode qui génère la definition et zou ! enfin zou ... plus facile à dire qu'a faire :p

**Comment by LaurentDardenne** [comment]
Au temps pour moi, j'avais à l'esprit _Find-FLowChartNodes_.
