### ISSUE TITLE
[Question] Version de Visual Studio utilisée ?

### ISSUE THREAD

**Issue by LaurentDardenne** [LxLeChat/FlowChartCore#30]
Est-ce une version Community  ?
Et le framework dotNet ciblé ? 4.0 ou 4.5 ?

**Comment by LxLeChat** [comment]
Salut Laurent,
J utilise vscode

Le framework euh.. je checkerai et e dirait ça plus tard

**Comment by LaurentDardenne** [comment]
Salut,
> J'utilise vscode

Ok.
Je n'ai pas encore utilisé VSCode en C# ayant VS sous la main (DGML).

> Le framework euh.. je checkerai et te dirait ça plus tard

Une version 'spécifique'.
https://www.nuget.org/packages/PowerShellStandard.Library/5.1.0
La dll native de PS est en dotNet 4.5 sur mon poste (W10)

**Comment by LxLeChat** [comment]
Netstandard2
C marqué dans csproj!
