### ISSUE TITLE
New-FLowChartGraph : Comportement du paramètre -CodeAsText. Ajouter le ou les noms d'exceptions dans un noeud Catch

### ISSUE THREAD

**Issue by LaurentDardenne** [LxLeChat/FlowChartCore#39]
L'ajout des noms d'exceptions gérée peut être utile : 
```powershell
$sb={
    "deux"
    try {
     $grade = 92
    } 
    catch [System.ApplicationException], [System.ArgumentException] {"un"}
    catch [System.ExecutionEngineException],[System.IO.DirectoryNotFoundException] {"deux"}
    catch {"trois"}
    Finally {
        "dispose"
    }
}
```
PS ajoutant en interne _System_ lors de la résolution de nom de classe je ne sais pas si ceci est identique (pour les exceptions de l'espace de nom System.xxx): 
```powershell
$sb={
    "deux"
    try {
     $grade = 92
    } 
    catch [ApplicationException], [ArgumentException] {"un"}
    catch [ExecutionEngineException],[IO.DirectoryNotFoundException] {"deux"}
    catch {"trois"}
    Finally {
        "dispose"
    }
}
```
ça reste à tester, car précises tjr le nom de classe complet.

**Comment by LxLeChat** [comment]
~~il me semblait que je gérais ces trucs la .. il faut que je regarde~~ 
rien du tout enfait .. !

**Comment by LxLeChat** [comment]
Voila déja une implémentation dans le CatchNode et ce que ça donne avec tes exemples:

Pour le premier cas:
```powershell
PS > $a[1].Children[1]

CatchTypes : {System.ApplicationException, System.ArgumentException}
Name       : CatchNode
Children   : {CodeNode}
Parent     : FlowChartCore.TryNode
Position   : 1
Depth      : 1
Id         : 0211
Graph      : {}

```

Pour le deuxième cas:
```powershell
PS > $a[1].Children[1]

CatchTypes : {ApplicationException, ArgumentException}
Name       : CatchNode
Children   : {CodeNode}
Parent     : FlowChartCore.TryNode
Position   : 1
Depth      : 1
Id         : 0211
Graph      : {}
```

après il faudrait le mettre comment dans le graph ??? t as une idée ?? faire des retour chariots dans le label du noeud ??

**Comment by LaurentDardenne** [comment]
Parfait.
> faire des retour chariots dans le label du nœud ??

Oui. Ensuite c'est une question de rendu, je sais pas si on peut jouer sur la taille de la police et la longueur max d'une ligne de label s'il en existe plusieurs .

**Comment by LxLeChat** [comment]
brut de décoffrage voila ce que ça donne:
![image](https://user-images.githubusercontent.com/43340127/97059660-51198400-1591-11eb-994d-564eb6763939.png)

si j arrivais à centrer catch ça serait bien non ??

**Comment by LaurentDardenne** [comment]
> si j arrivais à centrer catch ça serait bien non ??

Je trouve que c'est suffisant pour le moment, ensuite faut regarder [les possibilités](http://www.graphviz.org/doc/info/attrs.html#k:escString).

Merci.
