### ISSUE TITLE
New-FLowChartGraph : La longueur ne peut pas être inférieure à zéro.

### ISSUE THREAD

**Issue by LaurentDardenne** [LxLeChat/FlowChartCore#40]
Repro ( version ‎du dimanche ‎18 ‎octobre ‎2020, ‏‎14:52)* :
```
$sb={
    "deux"
    try {
     $grade = 92
    } 
    catch [System.ExecutionEngineException] {
            "deux"
            try {
                    $grade = 92
                    if ($grade -ge 90) { "Grade A" }
                    elseif ($grade -ge 80) { "Grade B"} 
                    elseif ($grade -ge 70) { "Grade C";break}
                    elseif ($grade -ge 60) { "Grade D" }
                    else { "Grade F"}
                    writeLog "Suite"
                    break
            } 
            catch [System.ExecutionEngineException] {"un"}
            catch [System.IO.DirectoryNotFoundException] {"deux"}
            catch {"trois"}
            Finally {
                "dispose"
            }
    }
    catch [System.IO.DirectoryNotFoundException] {
            "deux"
            try {
                $grade = 92
                if ($grade -ge 90) { "Grade A" }
                elseif ($grade -ge 80) { "Grade B"} 
                elseif ($grade -ge 70) { "Grade C";break}
                elseif ($grade -ge 60) { "Grade D" }
                else { "Grade F"}
                writeLog "Suite"
                break
            } 
            catch [System.ExecutionEngineException] {"un"}
            catch [System.IO.DirectoryNotFoundException] {"deux"}
            catch {"trois"}
            Finally {
                "dispose"
            }
    }
    catch {
            "deux"
            try {
                $grade = 92
                if ($grade -ge 90) { "Grade A" }
                elseif ($grade -ge 80) { "Grade B"} 
                elseif ($grade -ge 70) { "Grade C";break}
                elseif ($grade -ge 60) { "Grade D" }
                else { "Grade F"}
                writeLog "Suite"
                break
            } 
            catch [System.ExecutionEngineException] {"un"}
            catch [System.IO.DirectoryNotFoundException] {"deux"}
            catch {"trois"}
            Finally {
                "dispose"
            }
    }
    Finally {
            "deux"
            try {
                $grade = 92
                if ($grade -ge 90) { "Grade A" }
                elseif ($grade -ge 80) { "Grade B"} 
                elseif ($grade -ge 70) { "Grade C"}
                elseif ($grade -ge 60) { "Grade D" }
                else { "Grade F"}
                writeLog "Suite"
            } 
            catch [System.ExecutionEngineException] {"un"}
            catch [System.IO.DirectoryNotFoundException] {"deux"}
            catch {"trois"}
            Finally {
                "dispose"
            }
    }
}
Find-FLowChartNodes -ScriptBlock $Sb|New-FLowChartGraph -CodeAsText
New-FLowChartGraph : La longueur ne peut pas être inférieure à zéro.
```
ps : 
** Aucune méchanceté ici, mais sans gestion de version, c'est l'heure de compilation qui compte ;-)

**Comment by LxLeChat** [comment]
Ok je vais checker mais je pense que c lié au problème des trailing { ... ! 
Je crois qu il y a un soucis sur la methode discovercode... des histoires d offsets ! #32

**Comment by LxLeChat** [comment]
Avec la dernier version compilé j'ai pas d'erreur, si tu veux tester, et si c bon on clôtuuuuuuuUure !
Auto-Fusée!

**Comment by LaurentDardenne** [comment]
Même problème ( PS v5.1+ W10 Fr).
Ajout des traces simples (System.Diagnostics.Debugger.Log) utilisable avec debugView et/ou des assertions de debug.
Voir le stream verbose, là on a aucune info dans la console. 
Tu couples le tout avec des directives de compilation conditionnelle afin de livrer une version sans les traces de debug.

**Comment by LxLeChat** [comment]
oula tu me perds la :)
je dois ajouter ça ou ? tu veux dire dans le code c# ???

alors le problème vient du pipeline, il faut que je comprenne encore pourquoi.. mais si tu fais:
```powershell
$a = find-flowchartnodes -scripblock $sb
new-flowchartgraph -nodes $a
```
ça devrait fonctionner



Mon problème c'est que je ne sais pas comment débuguer les cmdlets powershell ^^ ni le code c# sous vscode ... ça serait super pratique ... en gros la à chaque fois je compile, j'ouvre une fenetre PS, j importe, et voila ... meme processus à chaque fois ! 
J'imagine qu'il y a un meilleurs moyen !
je crois que mon problème va se regler ... quand j aurais le temps de lire ça :
https://docs.microsoft.com/en-us/powershell/scripting/dev-cross-plat/vscode/using-vscode-for-debugging-compiled-cmdlets?view=powershell-7
et que je serai fatiger d'écrire ``console.Writeline("prout")`` xD

**Comment by LaurentDardenne** [comment]
> tu veux dire dans le code c# ???

Oui, comme [ici](https://github.com/LaurentDardenne/PSMap/blob/master/src/PSADigraph/PSADigraph/FunctionReferenceDigraph.cs#L7)
Un début de [doc](https://docs.microsoft.com/fr-fr/dotnet/csharp/language-reference/preprocessor-directives/preprocessor-if).

Pour les logs, le plus simple pour débuter je pense est d'adresser [DebugView](https://docs.microsoft.com/en-us/sysinternals/downloads/debugview). Pas besoin de plonger dans la doc d'un framewok de log (même si c'est souvent aisé à mettre en place). Ainsi on peut avoir les traces dans une fenêtre différente sans avoir a installer 'tous' les outils.

> alors le problème vient du pipeline, il faut que je comprenne encore pourquoi.. mais si tu fais:

Ok, je regarde ça.

> Mon problème c'est que je ne sais pas comment débuguer les cmdlets powershell 

Avec Visual Studio [on attache](https://docs.microsoft.com/fr-fr/visualstudio/debugger/how-to-debug-from-a-dll-project?view=vs-2019) le process. Avec [PS](https://www.powershell-scripting.com/index.php/forum/14-contributions-a-la-communaute/2921-astuce-cmt-utiliser-debugview-avec-ps#4085).
Il y a un petit bout de temps que je n'ai pas fait, à vérifier donc.

> J'imagine qu'il y a un meilleur moyen !

Tu m'étonnes !

>je crois que mon problème va se régler 

Si c'est comme le plugin PS, une fois configuré ça ne bouge plus.

**Comment by LaurentDardenne** [comment]
> ça devrait fonctionner

Oui cela fonctionne, mais il en manque pour aller au bout du scénario :  _-CodeAsText_

**Comment by LxLeChat** [comment]
oué .. enfait ça vient pas du pipeline  ... je racontais n'importe quoi... c effectivement la méthode discovercode .. !
je crois que je vais discreteeeeeeeeeement checker ça demain au taff ^^ !

**Comment by LaurentDardenne** [comment]
Un exemple, en précisant l'espace de nom '_using System.Diagnostics_;' : 

![image](https://user-images.githubusercontent.com/4894452/97042029-c0cb4700-1570-11eb-9497-584180be4d23.png)

On reste sur un dispositif similaire à _console.Writeline_, la différence est que la console n'est pas concernée.
Si on souhaite adresser plusieurs dispositifs à partir d'une seule écriture il faut [d'autres outils](https://stackify.com/nlog-vs-log4net-vs-serilog/).

**Comment by LxLeChat** [comment]
c bon je me suis créé un debug json :)
un peu de mal mais à force de forger je deviendrai forgeron !

btw, j'ai fixer l'issue, alors c encore un peu degueu la decouverte decode par moment ..  c dans la #32 ça !


c'est buildé et poussé !

**Comment by LxLeChat** [comment]
meilleur fix, je passe du coup de ça:
![image](https://user-images.githubusercontent.com/43340127/97054979-20801d00-1586-11eb-9c59-6d1b4cc3d9a7.png)

à ça:
![image](https://user-images.githubusercontent.com/43340127/97055029-37267400-1586-11eb-8a68-e85d7342be9d.png)
