### ISSUE TITLE
[Question] Ajout d'un script de build

### ISSUE THREAD

**Issue by LaurentDardenne** [LxLeChat/FlowChartCore#48]
La tâche de build ajoutée dans VS code ne peut être adressé en ligne de commande (je n'ai pas trouvé la syntaxe si elle existe).
L'usage d'une tâche VS Code utilisant un script de build externe permettrait de couvrir les deux usages.
Quelque chose comme ceci :
```powershell
dotnet build /property:GenerateFullPaths=true /property:WarningLevel=4 /property:WarningsAsErrors=CS1030 --output ..\Releases\bin --configuration Debug --no-incremental /p:DefineConstants="Test"
$LastExitCode
```
_DefineConstants_ permet de gérer les symboles du préprocesseur
```c#
#if Test
    #warning Attention
#else
    #error marche pas
#endif
``` 

_WarningsAsErrors_ au cas ou l'on souhaite considérer un warning comme une erreur.

_Configuration_ pour cibler le mode Debug ou Release: 
```c#
#if DEBUG
 #warning Compiled in DEBUG mode.  Do not ship this code.
#endif
```
_--no-incremental_ pour forcer la recompilation (sous réserve).

_--output ..\Releases\bin_ afin de compiler dans un répertorie de livraison, présent à la racine du projet. Une copie de fichier est aussi possible. Le contenu du répertoire Releases serait exclu du référentiel via .gitignore.

On peut simplifier et/ou construire la ligne de commande dynamiquement selon les options désirées.
L'étape suivante serait son intégration dans [Invoke-Build](https://github.com/nightroman/Invoke-Build/wiki/Concepts).

Enfin de renommer le répertoire Code en _src_, d'ajouter un répertoire _test_ permettrait de s'aligner sur un standard de structure de projet, par [exemple](https://gist.github.com/davidfowl/ed7564297c61fe9ab814).

**Comment by LxLeChat** [comment]
ehehe :) j'ai rien compris :p 
j'ai suivi le tuto de MS ^^ 

pour le build je fais "F1" puis "Tasks: Run build task"
pareil pour le debugueur j'ai pas tout compris ... je suis obligé de lui fournir le PID de mon process pwsh ... space .. j'ai fait ça en 10 min hier soir à 00h00 -_- 

faut que je regarde tout ça .. mais j'ai l impression que c un ocean de connaissances qu'il me manque la ...

**Comment by LaurentDardenne** [comment]
> ehehe :) j'ai rien compris :p

Ah !

>pour le build je fais "F1" puis "Tasks: Run build task"

Ici tu ferais par exemple :
```powershell
.\Build.ps1 -Release -Env Production # ou Test , dans ce cas on n'adresse pas les mêmes serveurs
```
>je suis obligé de lui fournir le PID de mon process pwsh

La dll étant chargée dans ce process, le debugeur doit donc [savoir](https://stackoverflow.com/questions/14598524/how-does-a-breakpoint-in-debugger-work) où placer le breakpoint.

> faut que je regarde tout ça .. mais j'ai l impression que c un ocean de connaissances qu'il me manque la ...

En même temps on ne construit pas une centrale nucléaire ;-)
C'est juste un condensé de simples pratiques de codage, ça casse pas trois pattes à un canard, 
Ici on souhaite les automatiser, on doit donc détailler les étapes et penser à quelque scénarios.
On peut faire 
```powershell
cd Code
dotnet build 
```
Cela fonctionne, mais c'est le contenu du fichier .csproj qui porte les directives et pas la ligne de commande. C'est statique.
En même temps, d'apprendre, c'est l'objectif de ton projet :-)

**Comment by LxLeChat** [comment]
ok,
le principe de build je l'ai en PS pur. La vu que c du dotnet j'avais tendance à builder "manuellement".
Du coup j'ai créé un ``build.ps1`` hyper simple, et j'ai renommé le repertoire ``Code`` en ``Src``, effectivement c'est plus logique.
Je vais continuer à voir si je peux améliorer le truc ... je vois pas trop ce que je peux faire de plus pour le moment ...
pour le debugage j'aimerai bien qu'il me lance un PS au lieu de me demander à quel PS m'attacher ...

**Comment by LaurentDardenne** [comment]
Avec ceci on peut démarrer le debuger depuis PS :
![image](https://user-images.githubusercontent.com/4894452/97084929-7900fa00-161a-11eb-8f35-b6fe10afd60c.png)
Mais aucune trace de VS Code :
![image](https://user-images.githubusercontent.com/4894452/97085083-63400480-161b-11eb-8596-036ae81c1d14.png)

[edit]
On doit au préalable charger le projet dans VS avec les droits admin

**Comment by LaurentDardenne** [comment]
Si tu aimes [la lecture](https://github.com/microsoft/vscode/issues/60070) ...

**Comment by LxLeChat** [comment]
bon c bon le launch.json fonctionne ! \o/
du coup j'ai renommé le rep code en src .. ça ma causé quelque problème ..... mais maintenant qd tu fais "F5" pour debug, ça build, et ça lance un nouveau pwsh et ça charge le module ! 
a la find de session de debug, il faut penser à fermer la fenetre pwsh à cause du blocage de dll

je viens d'ajouter une config de debug pour powershell aussi, faut pas oublier de selectionner le bon env de debug

**Comment by LxLeChat** [comment]
La script de build devrait aussi permettre la suppression/création du psd1
pi-être créer une github actions poru faire tout ça, au déclement d'un PR
Ca permetterai de ruler les tests sur différents types d'env (powershell, pwsh , windows  / linux)

concernant le psd1:
- il y a 2 ou 3 choses lors du build d un script, la version courante, un guid quelque part je ne me rappelle plus exactement
- voir si on peut chopper les dernier commits, pour les ajotuer dans les release notes
- ajouter un param, qui dit si on est sur de la mineur ou de la majeur, pour incrémenter la version
il faut que ça reste un truc simple, pour le coup vu que c'est déja compiler, la création du psd1 est relativement simple à faire !

cela impliquerait de ne plus faire des PR à chaque commit ...
@LaurentDardenne what do you think ?

dans un premier temps on ne serait pas obliger de mettre des versions (ou tout du moins rester sur une version unique)

A terme ça aurait l'avantage de faciliter la vie sur la publication psgallery

**Comment by LaurentDardenne** [comment]
> La script de build devrait aussi permettre la suppression/création du psd1

On ne le crée qu'une fois. C'est le versionning qui change à chaque itération.

>     * il y a 2 ou 3 choses lors du build d un script, la version courante, un guid 

Le guid est fixe.

>     * voir si on peut chopper les dernier commits, pour les ajouter dans les releases notes
ouai yaka...

>     * ajouter un param, qui dit si on est sur de la mineur ou de la majeur, pour incrémenter la version

Le numéro de version porte déjà l'information il me semble.

>       il faut que ça reste un truc simple, 

[:-)](https://github.com/LaurentDardenne/ParameterSetRules/blob/master/build.settings.ps1#L778)
Il y a peut être plus simple mnt.

> dans un premier temps on ne serait pas obliger de mettre des versions (ou tout du moins rester sur une version unique)
> A terme ça aurait l'avantage de faciliter la vie sur la publication psgallery

Le numéro de version est nécessaire pour différencier les packages, on ne peut pas livrer deux fois le même.
Plus tôt tu géres le numéro de version mieux c'est.
