### ISSUE TITLE
Escape characters

### ISSUE THREAD

**Issue by LxLeChat** [LxLeChat/FlowChartCore#51]
Pour tester, j'ai ajouté d'autres lignes de code, particulièrement ceci

 ``$ModulePath='G:\PS\FlowChartCore\Code\bin\Debug\netstandard2.0'`` 
On constate que le \n est interprété par la méthode compile il me semble, il y peut être qq chose à échapper dans ce cas.
``"0210"[label="#FlowChartCore init\l$projectPath=$PSScriptroot\l\l$ModulePath='G:\\PS\\FlowChartCore\\Code\\bin\\Debug\\letstandard2.0'",shape=box];``

**Comment by LxLeChat** [comment]
Donc y a un soucis la dessus...
Le seul moyen que j ai trouvé c est de ne pas tenté l alignement du texte a gauche dans le label. Laissé par defaut, alors seulement on a pas de soucis. Mais le rendu est moins sympa

**Comment by LaurentDardenne** [comment]
Il faut[ échapper ](https://graphviz.org/doc/info/attrs.html)comme dans les regex :
```
In addition, if the associated attribute is label, headlabel or taillabel, 
the escape sequences "\n", "\l" and "\r" divide the label into lines, centered, left-justified, and right-justified, respectively.

Obviously, one can use \\ to get a single backslash. 
A backslash appearing before any character not listed above is ignored.
```

**Comment by LxLeChat** [comment]
j'ai fixé l'issue avec une regex
```c#
            // fix issue #51
            // when there is a path  like c:\n\blalal the c:\n was transformed into c:\l
            Regex Rx = new Regex(@"(?<!\\)\\n");
            string compiledCleaned = Rx.Replace(compiled,"\\l");
            string compiledCleaned2 = compiledCleaned.Replace("\\r","\\l");
```

du coup plus de problème avec les path ...

**Comment by LaurentDardenne** [comment]
Vérifie ta correction, il y a une perte d'info :
```Powershell
$Rx = [Regex]::new('(?<!\\)\\n')
$Rx.Replace('c:\n\blalal',"\\")
#c:\\l\blalal       <--- on perd \n
$Rx.Replace('c:\n\blalal',"\\n")
# c:\\n\blalal
```
Une alternative devrait régler les 3 cas :
```Powershell
$Rx = [Regex]::new('(?<!\\)\\(n|r|l)')
$Rx.Replace('c:\nom\list\regex','\\$1')
# c:\\nom\\list\\regex
```
