### ISSUE TITLE
Switch: Ajouter le nom du paramètre s'il est précisé (-regex,-wildcard etc)

### ISSUE THREAD

**Issue by LaurentDardenne** [LxLeChat/FlowChartCore#54]
Les syntaxes suivantes étant possibles : 
```powershell
    switch [-regex|-wildcard|-exact][-casesensitive] -file filename
    {
        "string"|number|variable|{ expression } { statementlist }
        default { statementlist }
    }
```
Si l'une d'entre elles est précisée, on ne retrouve pas le nom du paramètre dans le rendu d'une instruction Switch.

**Comment by LxLeChat** [comment]
ça t irait comme ça ? 
![image](https://user-images.githubusercontent.com/43340127/97108901-b4f69680-16d0-11eb-9c0c-bd402fc79914.png)

**Comment by LaurentDardenne** [comment]
Le paramètre est une information portée par l'instruction Switch,  la dupliquer sur chaque cas est redondant.
De lire _switch -regex_ dans le texte du noeud est préférable je trouve.

**Comment by LxLeChat** [comment]
t as raison
![image](https://user-images.githubusercontent.com/43340127/97110952-4ae3ee80-16dc-11eb-956d-9d27ec67949c.png)


c poussé, si c'est good on clôture !
