### ISSUE TITLE
[Question] A propos d'une méthode

### ISSUE THREAD

**Issue by LaurentDardenne** [LxLeChat/FlowChartCore#60]
J'ai lu [ceci](https://github.com/LxLeChat/FlowChartCore/blob/master/Src/Library/Nodes%20-%20Keywords/BreakNode.cs#L82) qui me laisse perplexe, aucun des deux paramètres n'est utilisé...

**Comment by LxLeChat** [comment]
c'est juste l'override, comme ça depuis le haut si j'appelle ``GenerateGraph(bool recursive, bool codeAsText)``, c'est cette méthode qui est appellée sur tous les types de noeuds.
effectivement les arguments ne sont pas utilisé dans le cas d'un break, puisque il n y a pas d'enfants, ni dans le cas d un continue par exemple.
Du coup pour break, continue, exit etc... cette méthode fait exactement la meme chose que la méthode : ``public override void GenerateGraph(bool recursive)``

donc on pourrait refactorisé la méthode comme ceci je pense:
```c#
public override void GenerateGraph(bool recursive, bool codeAsText){
            GenerateGraph(recursive);
}
```
