### ISSUE TITLE
Add Cdmet base help

### ISSUE THREAD

**Issue by LxLeChat** [LxLeChat/FlowChartCore#61]
Faut voir comment faire en c# .. ça à l'air beaucoup plus lourd à faire qu'en PS .. mais c'est nécessaire !

**Comment by LaurentDardenne** [comment]
As-tu regardé [platyPS](https://github.com/PowerShell/platyPS) ?

**Comment by LxLeChat** [comment]
Ouais je connais platyps, mais c plus pour externaliser la doc de tes fonctions/modules vers du markdown.
La l idee c deja de faire l'aide basique en c# pour que le ``get-help find-flowchartnodes`` fonctionne

**Comment by LaurentDardenne** [comment]
> Ouais je connais platyps, mais c plus pour externaliser la doc de tes fonctions/modules vers du markdown.

Je ne l'ai pas utilisé depuis qq temps mais à relire [ceci](https://github.com/PowerShell/platyPS/blob/master/docs/New-ExternalHelp.md) il me semble approprié.
Il est utilisé dans ce [build](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/build.ps1#L136).

J'ai utilisé [ceci ](https://github.com/Crypt32/PsCmdletHelpEditor) à une période.
Je regarderais ça prochainement.

**Comment by LxLeChat** [comment]
oui mais pour l'instant il n y a meme pas de help sur les focntions dans la console :) c'est ça que je veux dire
si tu fais ``get-help find-flowchartnodes`` tu n auras rien 
```powershell
PS > get-help Find-FLowChartNodes

NOM
    Find-FLowChartNodes

SYNTAXE
    Find-FLowChartNodes [-ScriptBlock] <scriptblock>  [<CommonParameters>]

    Find-FLowChartNodes [[-LiteralPath] <string[]>]  [<CommonParameters>]


ALIAS
    Aucun(e)


REMARQUES
    Aucun(e)

```

**Comment by LxLeChat** [comment]
ah désolé je suis un peu lent ... 😸 
tu suggères que j utilise platyps pour générer un maml et que je le remplisse ensuite ???

parce que moi je partais sur un truc comme ça:
https://www.red-gate.com/simple-talk/dotnet/software-tools/documenting-your-powershell-binary-cmdlets/

en gros tu mets du xml dans ton code, et avec un petit exe ça te génère le maml

**Comment by LaurentDardenne** [comment]
> tu suggères que j'utilise platyps pour générer un maml et que je le remplisse ensuite ???

Tu ne fais rien, je vais regarder ça.

> en gros tu mets du xml dans ton code, et avec un petit exe ça te génère le maml

A voir avec [Sandcastle](https://github.com/EWSoftware/SHFB).

**Comment by LaurentDardenne** [comment]
Avec PsCmdletHelpEditor : 
![image](https://user-images.githubusercontent.com/4894452/97785142-8894bb80-1ba3-11eb-8f5e-ee687a60648e.png)

[CmdletHelpEdit.zip](https://github.com/LxLeChat/FlowChartCore/files/5469466/CmdletHelpEdit.zip)
Dans l'archive le fichier xml est à placer dans un répertoire nommé fr-fr à la racine du répertoire du module.

A voir à l'usage si ce soft est utile, par exemple en cas de modification et/ou d'automatisation de la génération.

**Comment by LaurentDardenne** [comment]
Avec PlatyPS, une fois le module chargé, on peut récupérer l'aide existante :
![image](https://user-images.githubusercontent.com/4894452/97785828-ca276580-1ba7-11eb-892b-c25b71a69596.png)

A vérifier. 
Ce qui fait une tâche de plus dans le build.

**Comment by LaurentDardenne** [comment]
> en gros tu mets du xml dans ton code, et avec un petit exe ça te génère le maml

Oui c'est une autre solution, mais dans ce cas il n'est possible d'avoir qu'un seul fichier d'aide, celui en anglais.
C'est un choix comme un autre.

**Comment by LxLeChat** [comment]
https://github.com/red-gate/XmlDoc2CmdletDoc

Check ça, ca reste "interne"

Du coup t ecris la doc direct dans le code

**Comment by LaurentDardenne** [comment]
Fais comme tu le sens ;-)

**Comment by LxLeChat** [comment]
Je me demande comment ils font pour les cmdlets Powershell par exemple...! 

https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.Commands.Management/commands/management/Computer.cs

Ils mettent du xml dans le code direct

**Comment by LxLeChat** [comment]
Je vais inclure platyps au build c une bonne idée ! Je crois qu on va rester sur ta solution aussi... l autre me semble galère finalement

**Comment by LaurentDardenne** [comment]
> Ils mettent du xml dans le code direct

Oui, mais ici on [documente](https://docs.microsoft.com/fr-fr/dotnet/csharp/codedoc) la classe C#. Voir [aussi](https://marketplace.visualstudio.com/items?itemName=k--kato.docomment)
Pour l'aide de PS, MS à un [autre process](https://github.com/MicrosoftDocs/PowerShell-Docs) qui cible l'aide off-line, online , l'aide 'updatable' et le site MicrosoftDoc (le SDK) ( si j'ai bien compris).

**Comment by LaurentDardenne** [comment]
Tu peux clore je pense.
