### ISSUE TITLE
No Begin Node

### ISSUE THREAD

**Issue by LxLeChat** [LxLeChat/FlowChartCore#62]
Je pensais qu'on avait un noeud "start of script" ... je me trompe peut-être ... !
on a bien le "End_of_script"

est ce que on met ces noeuds d'ailleurs ? quel nom leur donner ?
Begin of script ?
Start of script ?
même combat pour le noeud de fin ?

**Comment by LxLeChat** [comment]
Création d'une branche dédiée "Feature-StartOfScript"
https://github.com/LxLeChat/FlowChartCore/tree/Feature-StartOfScript

@LaurentDardenne qu'en penses tu ? je ne sais plus si on en avait déjà discuté de begin et end ??
j'ai implémenté la feature dans la nouvelle branche, du coup il y a un noeud "Start of script" qui apparait. Je ne sais pas si le nom est "bon" ou si c'est bien de faire ça .. ! moi je pense que c'est plutot intéressant d'avoir un "début"

**Comment by LaurentDardenne** [comment]
> @LaurentDardenne qu'en penses tu ?

Je n'ai pas trop de temps ces derniers jours.

> je ne sais plus si on en avait déjà discuté de begin et end ??

Rapido.

A mon avis la présence de nœud nommé 'début' et 'fin' n'a de sens que s'il y a plusieurs scriptblocks présent (conteneur) sur le graphique. Ensuite la présence de conteneur/SubGraph porte implicitement, par son rendu, cette information.

Lorsque je relis des graphiques générés à l'aide de FlowChartCore j'ai déjà le sentiment que parfois certains nœuds n'apportent aucune information.
Par exemple pour une instruction _If sans Else_, il n'existe pas de lien pour le _Else_ implicite mais un _End If_.

Selon moi le nommage n'est pas le plus important ici, en sachant que l'on a plusieurs de 'type de fin': de scriptblock -> de fonction -> de script -> de module.
Et puisque pour le moment l'utilisateur précise en entrée un scriptblock, il sait donc , à la différence des cacahuètes, quand il commence et quand il finit ;-)

**Comment by LxLeChat** [comment]
> Par exemple pour une instruction If sans Else, il n'existe pas de lien pour le Else implicite mais un End If.

intéressant ça ... ! effectivement on pourrait tracer un un else implicite... 
pour un simple block ``$sb = { if($x){ "something" } }`` un truc comme ça serait mieux ?
![image](https://user-images.githubusercontent.com/43340127/97626618-64619f00-1a2a-11eb-9b5c-8fa5d7dba249.png)


Concernant le end_if, j'ai fait ça pour mieux "voir" les choses et surtout car c'est plus pratique et plus propre pour tracer vers le noeud suivant.
Au début ce end_if était uniquement représenter par un "point".

quand tu passes la moulinette sur un gros script, c'est vraiment mieux de voir ce genre de choses je trouve ... après on mettre une autre info dedans, "end if: $x" par exemple pour que ça s'accroche mieux au if ..

> Et puisque pour le moment l'utilisateur précise en entrée un scriptblock, il sait donc , à la différence des cacahuètes, quand il c
commence et quand il finit ;-)

ok ok :) je mets pas de begin! par contre le end je trouve ça assez utile parce que quand tu as des 'exit'  ou des 'break' bizarre comme tu me l as montré, ça dirige le graph vers un point de "fin".
