### ISSUE TITLE
Migrate Everything to netcoreapp3.1

### ISSUE THREAD

**Issue by LxLeChat** [LxLeChat/FlowChartCore#73]
As discussed in issue #68 we will migrate everything from a compatible version across ps version to an only powershell 6+ compatible version.
This decision was made, mainly, because we could not deal with the  ternary expression, as ternaryexpressionAST is not part of netstandard2.0.

So basically, what i'm going to do is: 
Create a new project targeting netcoreapp3.1, referecing System.Management.Automation 7+, copy paste everything for the old project ... and boum !

**Comment by LxLeChat** [comment]
en revanche @LaurentDardenne ... j'ai une question pour toi ... j'ai tout migré mais j'ai fait ça comme un sale sur ma branche local master ... du coup toutes les autres branches vont devenir obsolètes il me semble ..
Sais tu si il y a une meilleur manière de faire les choses ??

(j'ai encore rien poussé vers github ^^ )

**Comment by LaurentDardenne** [comment]
Non désolé, j'ai un usage basique de Git.
A priori un Sync sur chaque branche + résolution de conflits ?

Les branches restantes sont de ton côté, j'ai supprimé celles des PR.
Et de mon côté je peux supprimrer le fork et le recréer une fois le master à jour.

**Comment by LxLeChat** [comment]
Bon voila c'est fait... ! chez moi ça fonctionne -_-!

**Comment by LaurentDardenne** [comment]
Merci.
Je regarde ça demain.

**Comment by LxLeChat** [comment]
La migration fonctionne sous windows, mais pas sous linux. #81
