### ISSUE TITLE
[Pour information] Construction basée sur l'opérateur ternaire

### ISSUE THREAD

**Issue by LaurentDardenne** [LxLeChat/FlowChartCore#74]
Un test qui met en évidence, selon moi, la difficulté de relecture de certaines construction et par la même l'utilité de l'outil : 
```powershell
$UseCases=@(
    @{isVersion=$true;X=$null}
    @{isVersion=$true;X=[pscustomObject]@{Property=$null}}
    @{isVersion=$true;X=[pscustomObject]@{Property=10}}

    @{isVersion=$false;X=$null}
    @{isVersion=$false;X=[pscustomObject]@{Property=$null}}
    @{isVersion=$false;X=[pscustomObject]@{Property=10}}

)

Describe 'Null Conditional Assignment Operator' {
 Context "When there is no violation" {
  It "Test strict mode <isVersion> with '<X>"  -TestCases $UseCases {    
    param($isVersion,$X)
         if ($isversion)
         { Set-StrictMode -Version latest;Write-Warning 'Latest'}
         else
         { Set-StrictMode -Off;Write-Warning 'Off'}

        $result=$x ?  ${x}?.property ? '[NCAO] X.Property is not null': '[NCAO] X.Property is null' :'[NCAO] X is null'
        Write-warning $result

        if ($null -ne $x)
        {
            if ($null -ne $x.property)
            {Write-Warning 'X.Property is not null'}
            else 
            {Write-Warning 'X.Property is null'}
        }
        else
        {Write-Warning 'X is null'}
  }
 }
}
```
On a 97 caractères du côté du nouvel opérateur contre 197 pour l'écriture classique.
Le défi : relire ce type de code à 9h du matin frais et dispo ou à 17h en étant un peu moins frais voir fatigué :-)

Il se peut que pour certaines construction (${x}?.property ) il ne soit pas nécessaire de les transformer dans le graph.

**Comment by LaurentDardenne** [comment]
ça on connait :
```powershell
 $X= $Y = $Z =10
```
mais ceci :
```powershell
 $x ??= $Y ??=  $Z ??=10
```
Pas certains que ce soit aisé à transformer, ni très utile de coder ainsi.

**Comment by LxLeChat** [comment]
ouais, de toute façon ça passera dans un code block ça  car ça reste de l'assignation de variable non ?
~~D'ailleurs je suis entrain de me dire que si on a des constructions comme ça:
`` $a = Invoke-Command -ScriptBlock {....}``  ou même ``$a = if () ...``on pourrait tet en faire quelque chose qd même ... qu en penses tu ?? parce que on peut très bien avoir des scripts qui sont entièrement  contenu dans ce genre de constructions.. !
(on en a déja parlé non ? je pensais tet à des subgraph pour ce genre de trucs ... )
ça serait tet l'occasion d'une nouvelle issue ???~~ bad idea!


Je vais déja essayer d'intégrer l'operateur ternaire au code ... ce we si j'ai le time! mais je vois mal le ce genre de constructions sans assignation de variable !

**Comment by LaurentDardenne** [comment]
> ouais, de toute façon ça passera dans un code block ça car ça reste de l'assignation de variable non ?

Pour le ternaire c'est l'usage de base, mais je n'ai pas étudier plus que ça les constructions possibles.
De partir sur cette hypothèse est un bon début.
J'ai déjà en stand by qq jeux de tests recopiés du repo Powershell.

> Je vais déjà essayer d'intégrer l'opérateur ternaire au code 

Je n'ai pas encore regardé le code C# et cela aurait été l'occasion, mais en ce moment je maintiens une appli codé en PS par le petit frère de Frankenstein (sans specs, sinon ce serait trop facile), j'ai donc un peu de mal à remettre le couvert le WE...

**Comment by LxLeChat** [comment]
Ahaha :)
Excellent! J ai connu ça aussi! D ou ce projet :)

**Comment by LaurentDardenne** [comment]
>D'où ce projet :)

Je suis d'accord, ceci dit documenter le n'importe nawak, il existe [qq excuses](https://www.jesuisundev.com/pourquoi-les-developpeureuses-codent-avec-le-cul/), n'est d'aucune aide.
FlowChartCore précisera la première impression, _p* t* n quel code de m*_ !

**Comment by LxLeChat** [comment]
Ok je vais l issue ouverte, de mon côté je touche à rien :) quand t auras envie de regarder ça sera une bonne occasion !
