### ISSUE TITLE
Problème Loading System.management.automation Ubuntu

### ISSUE THREAD

**Issue by LxLeChat** [LxLeChat/FlowChartCore#81]
Problème de chargement de system.management.automation quand on laod la dll flowchartcore.dll sous ubuntu. ! je sais pas pourquoi \o/
```
PS /Src/bin/Debug/netcoreapp3.1> Import-Module ./FlowChartCore.dll
Import-Module: Could not load file or assembly 'System.Management.Automation, Version=7.0.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (0x80131621)
```
argleuh

**Comment by LxLeChat** [comment]
Bon bah la migration a tout cassé pour linux \o/ et j'avoue que je comprends pas trop comment ces histoires de dépendances fonctionne la ... ça me parait super compliqué avec l'état actuel de mes connaissances ... moi qui pensait que ça serait du copy/paste ahaha ! du coup j'hésite limite à faire machine arrière ... :(

**Comment by LxLeChat** [comment]
J'ai effectué des tests ... enfait il va y avoir des gros souscis ... imaginon que sous linux tu as la version 7.0.1 et bien même si je resolvais les problème de dépendances etc ... cela ne fonctionnerai pas avec la version 7.0.3 de system.management.automation7.0.3 ... grosse galère .. ça sent le retour et netstandard tout ça ... !!!! j'ai vu qu il y avit un template dotnet pour les psmodule en version 7, mais malheureusement il ne fonctionne pas ... 

Malheureusement en l'état de mes connaissances je ne vois pas comment faire facilement ... @LaurentDardenne  si tu as une idée .. ! sinon je sens que ça va être retour à la case départ ... ! et ternaryexpression attendra .. !

**Comment by LaurentDardenne** [comment]
> Problème de chargement de system.management.automation quand on load la dll flowchartcore.dll sous ubuntu. ! je sais pas pourquoi \o/

La dll SMA est déjà chargé par contre la dll du projet référence une autre version de SMA. [A vérifier](https://github.com/Azure/azure-powershell/issues/11446)

>sinon je sens que ça va être retour à la case départ 

Ne jette pas le bébé avec l'eau du bain :-)
L'objectif est de documenter du code Powershell indépendamment de la plateforme. La plupart du code PS est sous Windows. Pour un usage sous Linux c'est forcément PS Core.
Un loader selon la version de PS et l'OS est envisageable Et de demander sur le repo de PS comment on procède dans ce cas est aussi possible, en ayant au préalable tenter de trouver une solution afin d'étayer la demande.

Il y a peut être la solution dans le build de PS, faut creuser ;-)
De toute façon ce pb tu le rencontreras plus tard un jour ou l'autre.

**Comment by LaurentDardenne** [comment]
[A voir ](https://docs.microsoft.com/fr-fr/dotnet/core/tools/csproj#runtimeidentifier)si la compilation diffère pour cibler [Linux](https://docs.microsoft.com/fr-fr/dotnet/core/rid-catalog#linux-rids)

**Comment by LxLeChat** [comment]
j'ai testé ça ne change rien
par contre la version de sma qu il y a sur ubuntu 18.04 est la v4.0.30319 ...
du coup je sais en quoi ça joue ...
mais je tatonne ... je fais des trucs sans comprendre \o/

[edit] de ce ce que je comprends... si on fait ça comme ça, ça fonctionnera que sur PS 7.0.3 ... pas sous 6 ni 7.0.1 par exemple

[edit] ok ... made some progress ... donc il semblerait que j'ai raison .. j'ai referencé SMA 7.0.1 au lieu de la 7.0.3 car sur mon wsl ubuntu j'ai PS 7.0.1 et la ça fonctionne (ça fonctionne aussi sous windows en PS 7.0.3)
Donc en gros le "moins" peut le plus, mais l'inverse n'est pas vrai ... du coup c'est super relou ... !
En revanche, j'ai ajouté ``<RuntimeIdentifiers>win10-x64;ubuntu.18.04-x64</RuntimeIdentifiers>`` pour faire des builds par version, et avec la SMA 7.0.1 je me suis rendu compte que je pouvais importer la version "windows" sous ubuntu, donc ça ne semble pas nécessaire ça. (je confirme, en rebuildan "normalement", ça importe bien)

[edit] Bon bah du coup le seul moyen d'être full compatible 7.x.x c'est de réfenrencé SMA 7.0.0
Avec SMA 7.0.0 ça fonctionne avec PS 7.0.1 (ubutun dans mon cas) et PS 7.0.3 (windows dans mon cas). Donc la compatibilité vers le haut semple bonne.
Je ne sais pas ce qu'apporte SMA 7.0.3 mais on peut oublier xD

[edit] du coup c'est bon .. je suis juste entrain de me battre avec le CI ...quand ça sera bon tout sera sur la master

**Comment by LxLeChat** [comment]
maintenant la question est la suivante: comment gérer les nouvelles version de SMA ?? ce qui serait le top ... !

**Comment by LaurentDardenne** [comment]
> Je ne sais pas ce qu'apporte SMA 7.0.3 mais on peut oublier xD

J'avais pris la dernière version en pensant que la dernière est toujours préférable, ici tjr étant à remplacer par 'souvent '.

> [edit] du coup c'est bon

Bravo !
Désolé je n'ai pas pu t'aider, ce sujet étant nouveau pour moi et je n'ai pas de machine Linux.

> maintenant la question est la suivante: comment gérer les nouvelles version de SMA ?? ce qui serait le top ... !

Je pense qu'il vaut mieux '[la poser à Dieu plutôt qu'a ses saints](https://github.com/PowerShell/PowerShell/issues)'
On trouve quelque informations, sur le repo PS, autour des modules utilisable sous Linux et Windows, mais peu sur les modules binaires devant être livré sur de multiples plateformes (et ceux existant ne semblent pas couvrir le cas rencontré). A moins qu'ici ce ne soit qu'une question de formation sur les outils (.Net) utilisés...

**Comment by LxLeChat** [comment]
~~Je crois que sma 7.0.3 apporte entre aute foreach -parallel~~ aucune idée enfait xD

Concernant linux @LaurentDardenne , je n ai pas linux non plus, mais j ai wsl! C comme ça que je check

J ai vu quelques trucs concernant les différents framework mais il est clair que je fais que toucher la surface pour l instant... c dur l auto formation à l arrache :)

**Comment by LaurentDardenne** [comment]
> Concernant linux @LaurentDardenne , je n ai pas linux non plus, mais j ai wsl! C comme ça que je check

Ok je regarderais si j'ai le temps, j'imagine qu'il faut reconstruire tout l'environnement de dev.

>c dur l auto formation à l arrache :)

Sans aide oui. Et la lecture du SDK est aride mais riche d'info. Ensuite on a pas commencé qu'il faut prêter attention à [la suite](https://blog.miguelbernard.com/net-5-the-breaking-changes-you-need-to-know-about/)  :-/
C'est le genre de truc où tu te dis que t'aimerais avoir 4 bras, 2 cerveaux et des journées de 48 heures...

**Comment by LxLeChat** [comment]
>Ok je regarderais si j'ai le temps, j'imagine qu'il faut reconstruire tout l'environnement de dev.

euh je sais pas, moi je ne fait que charger le module pour le tester c'est tout :)
