### ISSUE TITLE
Module FOlder

### ISSUE THREAD

**Issue by LxLeChat** [LxLeChat/FlowChartCore#87]
@LaurentDardenne question pour toi: y a une raison pour que le répertoire Module soit dans le répertoire Src ??
on peut le remonter à la racine ou pas ???

parce que ça fait une semaine que je galère avec les github actions la ... et bref :)

**Comment by LxLeChat** [comment]
Enfait je suis un gros nul :)
euh autre questin, les fichier d'aides
```
---
external help file: FlowChartCore.dll-Help.xml
Module Name: FlowChartCore
online version:
schema: 2.0.0
---
```

Il ne faudrait pas plutot que external help file soit : ``external help file: Find-FlowChartCore.dll-Help.xml`` ???

**Comment by LaurentDardenne** [comment]
Salut,
>y a une raison pour que le répertoire Module soit dans le répertoire Src ?

Le répertoire Source contient toutes les sources du projet module et code C#.
Cela me semblait plus simple de tout regrouper.

> on peut le remonter à la racine ou pas ???

Si tu le souhaites, quel est le pb que tu rencontres avec Github actions  ?


> euh autre question, les fichiers d'aides
> Il ne faudrait pas plutôt que external help file soit : `external help file: Find-FlowChartCore.dll-Help.xml` ???

[La convention de nommage](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comment_based_help?view=powershell-5.1#externalhelp), il me semble, cible le module pas le cmdlet. Il contient l'intégralité de l'aide des cmdlets.

**Comment by LxLeChat** [comment]
petit problème chaise clavier ...  bref :)
je crois que j'ai réussi à  faire ce que je voulais, juste cette histoire de generation de xml, donc je check ça et je metterai le CI en place
