### ISSUE TITLE
Get-FlowChartNodes: encapsluser l'exception ParseException

### ISSUE THREAD

**Issue by LaurentDardenne** [LxLeChat/FlowChartCore#93]
Je trouve que le fait de redéclencher _ParseException_ est parfois un peu confus à comprendre dans la console : 

![image](https://user-images.githubusercontent.com/4894452/100541303-4cf11e00-3243-11eb-8117-355f63999fe3.png)

A la place indiquer _Impossible d'analyser le fichier/code : **$PourTellesRaisons**_ aiderait à comprendre que c'est une erreur d'analyse du fichier/code en entrée et pas une erreur de codage du cmdlet.
Je n'ai pas testé si dans ce cas c'est une erreur bloquante ou pas.

$PourTellesRaisons serait porter par la propriété _Innerexception_

**Comment by LaurentDardenne** [comment]
Par exemple on peut rencontrer ces messages : 

> Workflow is not supported in PowerShell 6+.


>  using module apartmentpets
>  Could not find the module 'apartmentpets'.


> Import-DSCResource -Module nx
> Could not find the module 'nx'.

> Executable script code found in signature block.

**Comment by LxLeChat** [comment]
sorry je me suis trompé dans le referencement de l'issue ... c'était 92 et pas 93 !
Du  coup je comprends pas bien cette problématique 
c'est dans le cas d'un ps 5.1 ??? tu  voudrais un message explicite c'est ça ??

**Comment by LaurentDardenne** [comment]
>tu voudrais un message explicite c'est ça ??

Dans certains cas on peut passer un peu de temps à comprendre quelle est la cause de l'erreur.
Ce n'est pas seulement le message mais une exception spécifique.
Exemple : 
```powershell
Get-FLowChartNode '.\ExistNoParseException.ps1','.\NoExist.ps1','.\ExistWithParseException.ps1','.\ExistButLocked.ps1'
```
Ici on peut avoir 3 cas d'erreur distincts, à mon avis on ne devrait déclencher qu'une exception identique  "Impossible de construire les nœuds à partir du fichier XYZ' et sa propriété _InnerException_ contiendrait la cause réelle.

Un exemple : 
```powershell
'$Ht=@{"Un"=}'> 'C:\temp\test.ps1' 
try { Get-FLowChartNode  'c:\temp\test.ps1' } catch [System.Management.Automation.ParseException] {write-warning "parse :`r`n $_"}
#WARNING: parse :
# At line:1 char:12
#+ $Ht=@{"Un"=}
#+            ~
#Missing statement after '=' in hash literal.

#autre cas
try { Get-FLowChartNode  'c:\temp\est.ps1' } catch [System.Management.Automation.ParseException] {write-warning "parse :`r`n $_"}
#Get-FLowChartNode: Cannot find path 'C:\temp\est.ps1' because it does not exist.
```
On peut bien évidement procéder ainsi :
```powershell
try { Get-FLowChartNode  'c:\temp\est.ps1' } catch {write-warning "ça marche pas !"}
```
Ok, mais qu'est-ce qui ne marche pas ...

Si je prend exemple sur un cmdlet :
```powershell
G:\PS\FlowChartCore> test-connection srv1,localhost,srv
#Test-Connection: Testing connection to computer 'srv1' failed: Cannot resolve the target name.
#
 #  Destination: localhost
#
# Ping Source           Address                   Latency BufferSize Status (ms)        (B)
# ---- ------           -------                   ------- ---------- ------
 #  1 localhsot            ::1                             0         32 Success

$Error[0].exception|select *

#TargetSite     :
#StackTrace     :
#Message        : Testing connection to computer 'srv' failed: Cannot resolve the target name.
#Data           : {}
#InnerException : System.Net.Sockets.SocketException (11001): Hôte inconnu.
#                   at System.Net.NameResolutionPal.ProcessResult(SocketError errorCode, GetAddrInfoExContext* context)
```
